### ISSUE TITLE
Design Mozilla Mailbox postcards

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/Design#107]
In Mozlando one of the work teams talked about instituting a physical mail program to welcome new hires, give kudos, etc. Each new hire would get a set of postcards to mail to whomever they wanted.

Regardless of whether the program pans out, it'd be really really awesome to have a set of illustrations we could pull from to use for postcards. Off the top of my head – 
- dapper fox by @natalieworth and @lovegushwa
- @kristinashu's other xray goggles characters 
- money fox by @natalieworth 
- @vazquez's globe from way back webmaker
- maybe @flukeout's dribbble illustrations?

Probably others! New ones would be great too.

**Comment by natalieworth** [comment]
Here's links to Kristina's dapper fox and money fox illustration from the EOY work: 
Dapper Fox: https://drive.google.com/a/mozillafoundation.org/file/d/0B20-0lpP23c0VlR4b3pWeWhmMFE/view
Money Fox: https://drive.google.com/a/mozillafoundation.org/file/d/0B20-0lpP23c0WnUzUkk5ZVo1dDg/view
It would be cool to update Money Fox with some colour too! We only included one colour for the t-shirt due to costs, but a postcard could definitely include more colours. Could be neat too to include a pattern option (similar to the one used for MozFest) but perhaps with different illustrations?

**Comment by davidascher** [comment]
Love to see this idea sprout.

**Comment by lovegushwa** [comment]
@cassiemc @kristinashu 
This could be a cool way to develop and test new illustration styles / see how they resonate with Mofo peeps. Also I would love to print some on the RISO at my house :)

**Comment by natalieworth** [comment]
I want a riso print! @lovegushwa

**Comment by cassiemc** [comment]
Yes I like that purpose too @lovegushwa and I too want one or some!
I might start throwing inspiration in here that I see around.
![image](https://cloud.githubusercontent.com/assets/1186326/11873724/14a1021c-a4aa-11e5-8ee6-0f15725bcfaf.png)
Imagine that with a pithy inspirational quote about open source or open internet.

**Comment by flukeout** [comment]
Something like this @cassiemc ?

![image](https://cloud.githubusercontent.com/assets/25212/11876939/1e6a7066-a4a1-11e5-938e-95cb21f0ff6e.png)

**Comment by cassiemc** [comment]
lol, YESSSSSSS @flukeout !!!! Make it so!!!

**Comment by lovegushwa** [comment]
haha! I love the tags flying out @flukeout

**Comment by cassiemc** [comment]
Moar thoughts. We could use the words / concepts from our design principles to create this beautiful set of cards. #39 That might lend the set some cohesion, even if the styles are different. 

Also, @ldecoursey filed https://github.com/MozillaFoundation/plan/issues/660 about making more swag for the Brooklyn office. This could be an excellent project for that. Updating milestone and Plevel to reflect that.
