### ISSUE TITLE
Write shared chapter on working w/ engineers

### ISSUE THREAD

**Issue by toolness** [MozillaFoundation/Design#11]
So there's also a [MoFo-Engineering-Handbook](https://github.com/MozillaFoundation/MoFo-Engineering-Handbook), and I thought it might be cool to have a chapter that's *shared* between both handbooks on how designers and engineers can successfully collaborate.

Alternatively, the design handbook could have a chapter on working with engineers, and the engineering handbook could have a chapter on working with designers.

Here's a thing @iamjessklein wrote while we were in Portland that might be useful for inspiration:

https://etherpad.mozilla.org/mybffengineer

**Comment by cassiemc** [comment]
Although this bug is over a year old, this is a process we can definitely continue to improve, especially based on feedback from our Mozlando retrospective. 

Wondering if @vazquez could take a stab at this in the new year? You are designer and dev wrapped up in one, and have had great success working with @scottdowne, so I'd expect you to have insights here.

The thinking and the sharing of those thoughts seem most important, rather than the documentation in a wiki, necessarily. Open to ideas for how this eventually manifests.

**Comment by cassiemc** [comment]
@vazquez In the next heartbeat, I'd love if you could set up a conversation with relevant designers and frontend engineers to continue the conversation we had last year.

**Comment by cassiemc** [comment]
@vazquez Any update here? Curious if working on mattermoz & calypso have opened up any doors for this conversation.

**Comment by vazquez** [comment]
Yes! I have created a [list of questions](https://docs.google.com/a/mozilla.com/document/d/1ilw0F_l71bVZk4fEuE8Ks-owaMWNqUuKtkadUyzs_Ls/edit?usp=sharing) to ask developers. I have booked time with Mavis and Gavin. My aim is for each interview to take no more than 15 minutes.

I will create a Google Form (we discovered this is a better approach when conducting research) so we can discuss results as a team.

**Comment by cassiemc** [comment]
Awesome progress, thanks @vazquez :)

**Comment by cassiemc** [comment]
@vazquez Can you update this please? Seems ready to close as long as next steps are filed

**Comment by vazquez** [comment]
Filing separate issues right after closing this one.
