### ISSUE TITLE
[Styles & Presets] Layout Grids & Frames

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#1166]
Reviewing this [responsive design chapter](https://www.figma.com/file/0OeKTKrj692DbAxwdEPsy1/3.-Responsive-Design-(Copy)?t=EsLJwWe9bdL3WgwB-6) could be a good discussion starting point

- [x] Chat with devs on their advice for breakpoints and grids (this was discussed at Design/Dev sync)
- [x] Decide breakpoints and standard frame sizes for desktop, tablet, and mobile
~- [ ] Standardize layout grids~ _I've been building to reflect what exists on production_

_______

# Design
### 1. Audit and research

- [x] Identify all unique use cases
- [x] Gather links to all documentation
- [x] Look up frequency of use to determine priority
- [x] (Optional) Gather links to useful information on how to craft atom/molecule/component

### 2. Component crafting
- [x] Build: All colors, text styles, and spacing should use defined tokens where applicable
~- [ ] States: Create all the necessary states (Active, hover, disabled)~
- [x] Accessibility: Meet applicable a11y ~and localization standards (reference the [checklist](https://webflow.com/accessibility/checklist#start))~ adapted for color and contrast vision impairment 
  - [x] Determine what accessibility issues might come up
 ~- [ ] Test against localization needs (content length)~
- [x] Create responsive states (Desktop, tablet, mobile)
~- [ ] Prototype: If applicable, hook up interactions for prototyping~
~- [ ] Define all editorial/content standards (ex. max characters, min/max width)~

# Documentation
- [x] Layer Naming: Format all layers and name with meaningful values
~- [ ] Variants and Component Properties Naming: correctly named and consistent _(goal is to make it easy to find in the library e.g. Component / State / Device)_~ we are defining grids as styles not components
- [x] Write spec description
   - [x] How and when to use it (explain everything that’s editable, customizable and available in simple and succinct terms)
   - [x] Show all possible variations
     - [x] States
     ~- [ ] Variants~
     - [x] Show some examples in context

# Acceptance Criteria

### 1. Audit & Research
- [x] As a Mozilla designer I can find the process work for the grids and frames in the Audit file

### 2. Design
_As a Mozilla designer I …_

- [x] Build: can update all colors, text styles, and spacing use defined tokens where applicable
- [x] States: can easily swap between states (Active, hover, disabled) and variants
- [x] Responsiveness: can easily access all breakpoint states (Desktop, tablet, mobile) and resizing does not break the component
- [x] Prototype: can easily use the grid styles and frame presets in a prototype with interactions already preset/hooked up
- [x] Accessibility: can see that all applicable a11y and localization standards (reference the checklist) have been met

### 3. Documentation
_As a Mozilla designer, I see that:_

- [x] All layers been named properly
- [x] All variants and component properties have been named properly
- [x] The spec description explains function and editability
- [x] All editorial/content standards (ex. max characters, min/max width) have been defined 
- [x] Variations have been listed
- [x] There are examples in context

_As a new Mozilla designer or contractor, I …_

- [x] Can easily discover frame presets and grid styles
- [x] Can easily find this frame presets and grid styles using the asset finder using the MoFo Design’s naming conventions
- [x] Can easily understand what the frame presets and grid styles are, how to use it and what edits can be made to it

**Comment by sabrinang** [comment]
**Figma Frames**
For standardizing what we use for desktop figma frame preset, we were deciding between using _"Desktop 1440x1024"_ or _"MacBook Pro 16" 1728x1117"_ 

<img width="1480" alt="image" src="https://user-images.githubusercontent.com/2492510/234675019-5ecff0d0-2731-4293-8c14-8ffc075c1a0d.png">

I wanted to confirm our decision as it sounded like we're going with _Desktop_ to accommodate more of our users screens but I also heard we wanted more screen width to design with which may imply using _MacBook Pro 16"_. 

Mapping what frame/grid would be used with audience screen resolutions (GA4 stats):
<img width="300" alt="image" src="https://user-images.githubusercontent.com/2492510/234678897-6b82c6df-e884-4330-bb7c-f130cf047aee.png">

Based on audience usage and that the columns/container grid is identical for both _(uses Desktop Extra Large)_, I have documented _Desktop 1440x1024_ figma preset as our go to.

Note: I think if we want more container width to design with that would require introducing and defining a new breakpoint for wider grid. If the designer decides to use wider screens for mockups that is okay but by default (and I assume desktop components) will use _Desktop 1440x1024_ to be included.    
_________
**Grid Styles**
<img width="150" alt="image" src="https://user-images.githubusercontent.com/2492510/234681280-78121624-3687-40a9-802c-1ab2658411f5.png">
I have defined five styles to reflect what is on production site however we will mainly be using three. Since this isn't a component, using the . naming convention doesn't hide it from the list but used that here to indicate these aren't the main ones used. I'm also looking for feedback for:
- if these are finalized, should I move these "grid styles" to the styles library (since this isn't a component and have not created grid components as grid styles are the most useful) as I don't think these belong under "atoms"?
- When do I sunset the previous page in style library and replace/update what currently existed? (separate ticket or part of this publication phase)
- any other way to name or organize the grid styles so it is clear three are mainly used? (do you think it is useful to have the other two defined in figma?)

**Comment by sabrinang** [comment]
tagging @nancyt1 for review
_(we will also chat through how this review process goes as we figure out the process)_

**Comment by sabrinang** [comment]
since I chatted with Nancy yesterday, tagging @beccaklam for review!

**Comment by beccaklam** [comment]
Hi @sabrinang this looks good to me to publish. Re:

> Note: I think if we want more container width to design with that would require introducing and defining a new breakpoint for wider grid. If the designer decides to use wider screens for mockups that is okay but by default (and I assume desktop components) will use Desktop 1440x1024 to be included.

I agree, I think this is something we can explore later, once we have a practical application for it.

For _.Large_ and _.Small_ I wonder when we'll use them. If we're not really using them it would make sense to hide them somewhere. The only situation I can think of is for testing to see if a design is scaling nicely. If we go that route perhaps we could add something to their naming that indicates these breakpoint sizes are mainly used for testing? Otherwise it might be confusing to a contractor why we have 5 sizes but only use 3 breakpoints.

**Comment by sabrinang** [comment]
Thanks for the review and feedback @beccaklam!
 
I removed the two additional grid styles that we wouldn't be using in mockups. The breakpoints and grids are still documented as it reflects what is live on the website but documented the grid style settings in [iterating grid styles](https://www.figma.com/file/sOxNGYMzwZT0B9Fal2D4WT/Component-Library?node-id=1051%3A6888&t=vP9HVwna9mWhzTNI-1) section if we need it for future reference. 

Since the grids are styles and not components I moved the three grid styles to the [Design Style Library](https://www.figma.com/file/JT9Dvdyc96AqQ3HJlnA9Qq/WIP-Mozilla-Foundation-Design-Style-Library?node-id=312%3A354&t=Z8SvpUmYhTjPNylg-1) file and published them. Also in the Design Styles Library file, I removed the old documentation and grid styles and relocated them to a separate [Archive](https://www.figma.com/file/EMjtNMAz1xurM5CBiHzptz/Archive?node-id=1-24) file to keep the file clean while still being able to reference the old grid elsewhere if needed.

This is noted in the Design Styles Library file seen in version history: 
<img width="200" alt="image" src="https://user-images.githubusercontent.com/2492510/235545829-cbfc4e07-5f79-4d54-96c2-882c511a6627.png">

There is nothing to publish in the Components Library as we are using grid styles and not any column components but keeping the documentation and process work there for now.
