### ISSUE TITLE
[File Presentation] Component Criteria

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#1167]
[Criteria Doc](https://docs.google.com/document/d/1-BYqdl2uM5lRT8zAtoy0Wussj590HAy8dYPs9dFFSPw/edit#bookmark=id.4jf6tqshx877)

Create component criteria checklist that can be reused for every new component.

**Comment by nancyt1** [comment]
Started putting together this component in [figma](https://www.figma.com/file/l2sg5G9EoQ8teLLZ1r9sbw/File-Presentation-Templates?node-id=374%3A896&t=6v8FthXtuJyH3scu-1), everything is still a WIP

**Comment by nancyt1** [comment]
On the [Crafting Component Templates](https://www.figma.com/file/l2sg5G9EoQ8teLLZ1r9sbw/File-Presentation-Templates?node-id=346%3A884&t=NnvHkCz2ZL7QBlm0-1) page, We've semi decided that having a checklist in figma might be duplicating work since there's already a checklist in github. We are still refining how documentation could be organized.

**Comment by nancyt1** [comment]
Created a follow up ticket to continue this work #1180
