### ISSUE TITLE
[Atoms] Buttons & Links

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#1168]
### Design
_1. Audit and research_
- [x] Identify all unique usage instances
- [x] Gather links to all documentation
- [x] Look up frequency of use to determine priority
- [ ] (Optional) Gather links to useful information on how to craft atom/molecule/component

_2. Component crafting_
- [x] Build: All colors, text styles, and spacing should use defined tokens where applicable
- [x] States: Create all the necessary states (Active, hover, disabled)
- [x] Accessibility: Meet applicable a11y and localization standards (reference the checklist)
- [x] Determine what accessibility issues might come up
- [x] Test against localization needs (content length)
- [x] Create responsive states (Desktop, tablet, mobile)
- [x] Prototype: If applicable, hook up interactions for prototyping
- [x] Define all editorial/content standards (ex. max characters, min/max width)

### Documentation

- [x] Layer Naming: Format all layers and name with meaningful values
- [x] Variants and Component Properties Naming: correctly named and consistent (goal is to make it easy to find in the library e.g. Component / State / Device)
- [x] Write spec description
- [x] How and when to use it (explain everything that’s editable, customizable and available in simple and succinct terms)
- [x] Show all possible variations
   - [x] States
   - [x] Variants
- [x] Show some examples in context

### Acceptance Criteria
**1. Audit & Research**
- [x] As a Mozilla designer I can find the process work in the Audit file

**2. Design**

_As a Mozilla designer I …_
- [ ] Build: can see that all colors, text styles, and spacing are using defined tokens where applicable
- [ ] States: can easily swap between states (Active, hover, disabled) and variants
- [ ] Responsiveness: can easily access all breakpoint states (Desktop, tablet, mobile) and resizing does not break the component
- [ ] Prototype: can easily use the component in a prototype with interactions already preset/hooked up
- [ ] Accessibility: can see that all applicable a11y and localization standards (reference the checklist) have been met

**3. Documentation**

_As a Mozilla designer, I see that:_
- [ ] All layers been named properly
- [x] All variants and component properties have been named properly
- [ ] The spec description explains function and editability
- [x] All editorial/content standards (ex. max characters, min/max width) have been defined
- [x] Variations have been listed
- [ ] There are examples in context

_As a new Mozilla designer or contractor, I …_
- [x] Can easily discover the button component
- [x] Can easily find this component using the asset finder using the MoFo Design’s naming conventions
- [ ] Can easily understand what this component is, how to use it and what edits can be made to it

**Comment by nancyt1** [comment]
This is ready for your review @sabrinang!

**Comment by sabrinang** [comment]
@nancyt1 I did a review and overall looking so good and comprehensive! I left feedback on stickies around the documentation portion closer to the context:
<img width="647" alt="image" src="https://user-images.githubusercontent.com/2492510/235199362-651e2be0-5e92-4173-8351-e6a50920663d.png">

### Review recap:
- **Description:** all components have “how to use this component field” in component configuration filled out except for: CTA Link & Social Vertical Block
- **Component crafting:** Pop buttons aren't reflecting what is on production and its states (you can reference what I made a [fundraising banner prototype](https://www.figma.com/file/2TK8tXeDIiLC67TMdbMIcO/Fundraising?node-id=116%3A273&t=57t2r45rCghrEkOc-1) if it helps)
- **Usage:** If social buttons shouldn’t be used individually, should they use . naming convention to hide from Assets panel or do we leave them?
- **Build, editability and usage (buttons):** Instead of deep-selecting into each layer to find their component property controls, exposing nested instances allows designers to click just the top-level component to also know that the icon boolean prop and text prop is something they can edit from the button component level (not needing to know to go to .base level)
- **Build, editability and usage (CTA links):** if different weights and colors are used for the component, should they be variants the user select instead of deep clicking to override? consider if we can build it in the component (or expose as a nested instance) so it is obvious and intentional we can change weight/text from the component level 
- **Responsiveness:** for full width buttons also note to set appropriate constraints so it scales with container?
- **Regarding components that aren't used on their own:** note for our future selves when we have navigation built out, hide what we should not use on their own with . naming convention (but do so when we have navigation components)
- **Interactivity:** some prototype connections are missing on hover

**Comment by nancyt1** [comment]
All feedback has been addressed. For the pop buttons, we decided to prototype the interaction separately and use a more responsive but static version to design with. I've also created individual components for the social buttons to more accurately reflect the hover states. Ticket is done and will be published soon.
