### ISSUE TITLE
Sunset /brand

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#1174]
We have refreshed our design pages at /design and will move away from /brand since it is too broad and /design is more representative of us.

## Unpublish old pages
- [x] Unpublish all the old /brand pages
- [ ] If there are no issues, then we can delete the pages a couple months after they have been unpublished 

#### Overview
- [x] https://foundation.mozilla.org/docs/brand/ -> https://foundation.mozilla.org/docs/design/
- [x] [new page, no action required] https://foundation.mozilla.org/docs/design/about/

#### Templates
- [x] https://foundation.mozilla.org/docs/brand/templates/ -> https://foundation.mozilla.org/docs/design/branding/templates/

#### Process
- [x] https://foundation.mozilla.org/docs/brand/process/ -> https://foundation.mozilla.org/docs/design/websites/ 
- [x] https://foundation.mozilla.org/docs/brand/process/collaboration/ -> https://foundation.mozilla.org/docs/design/collaboration/
- [x] https://foundation.mozilla.org/docs/brand/process/process-for-uxui-projects/ -> https://foundation.mozilla.org/docs/design/websites/process-for-uxui-projects/
- [x] https://foundation.mozilla.org/docs/brand/process/video-production-guidelines/ -> https://foundation.mozilla.org/en/docs/design/graphics/video
- [x] https://foundation.mozilla.org/docs/process/work-with-us/ -> https://foundation.mozilla.org/docs/design/about/

#### Brand & Identity 
- [x] https://foundation.mozilla.org/docs/brand/brand-identity/ -> https://foundation.mozilla.org/docs/design/branding/what-is-branding/
- [x] https://foundation.mozilla.org/docs/brand/brand-identity/expression/ -> https://foundation.mozilla.org/docs/design/graphics/
- [x] https://foundation.mozilla.org/docs/brand/brand-identity/design-tokens/ -> https://foundation.mozilla.org/docs/design/websites/design-tokens/
- [x] https://foundation.mozilla.org/docs/brand/brand-identity/logos/ -> https://foundation.mozilla.org/docs/design/branding/ 
- [x] https://foundation.mozilla.org/docs/brand/brand-identity/color/ (color is already unpublished) -> https://foundation.mozilla.org/docs/design/branding/#color
- [x] https://foundation.mozilla.org/docs/brand/brand-identity/Typography/ (typography is already unpublished) -> https://foundation.mozilla.org/docs/design/branding/#typography
- [x] https://foundation.mozilla.org/docs/brand/brand-identity/iconography/ -> https://foundation.mozilla.org/docs/design/graphics/illustrations/#iconography
- [x] https://foundation.mozilla.org/docs/brand/brand-identity/photography/ -> https://foundation.mozilla.org/docs/design/imagery/photography/
- [x] https://foundation.mozilla.org/docs/brand/brand-identity/illustration/ -> https://foundation.mozilla.org/docs/design/graphics/illustrations/
- [x] https://foundation.mozilla.org/docs/brand/brand-identity/ui-components/ -> https://foundation.mozilla.org/docs/design/websites/
- [x] https://foundation.mozilla.org/docs/brand/brand-identity/social-media/ -> https://foundation.mozilla.org/docs/design/marketing/ 
- [x] https://foundation.mozilla.org/docs/brand/brand-identity/theme-page-trustworthy-ai/ -> https://foundation.mozilla.org/docs/design/graphics/#trustworthy-ai
- [x] https://foundation.mozilla.org/docs/brand/brand-identity/theme-page-mozilla-festival/ -> https://foundation.mozilla.org/docs/design/branding/sub-brands/mozilla-festival/
- [x] https://foundation.mozilla.org/docs/brand/brand-identity/theme-page-privacy-not-included/ -> https://foundation.mozilla.org/docs/design/branding/sub-brands/privacy-not-included/ 

#### Agency Assets
- [x] https://foundation.mozilla.org/docs/brand/agency-assets/ -> https://foundation.mozilla.org/docs/design/branding/

#### Accessibility
- [x] https://foundation.mozilla.org/docs/brand/accessibility/ -> https://foundation.mozilla.org/docs/design/websites/accessibility-guidelines/
- [x] https://foundation.mozilla.org/docs/brand/accessibility/pdfs/ -> https://foundation.mozilla.org/docs/design/websites/accessibility-pdfs/

#### New
- [x] [new page, no action required] https://foundation.mozilla.org/docs/design/websites/

**Comment by kristinashu** [comment]
@sabrinang no rush, but could you please review this to double check everything before I action on it?

**Comment by kristinashu** [comment]
@sabrinang please let me know if you won't be able to get to this

**Comment by sabrinang** [comment]
@kristinashu I reviewed the links and pages, here is some feedback: 

**Process**

- Video production guidelines can be shortened to just video or videography (which matches other names)
    - Change page heading to video as well? Motion feels like it would talk about animation and motion we use but we don’t have that documented yet outside of videos yet

- Will we still be referencing https://foundation.mozilla.org/en/docs/process/work-with-us/ if we have _How we prioritize work, plan and execute UX/UI work_ on our about page https://foundation.mozilla.org/en/docs/design/about/?
   - I know it isn’t a /brand page but thinking about sunsetting links but I’m not too sure what references that as it refers to us as “engagement team” still fyi

**Brand & Identity**
- I’m not sure how specific the redirects need to be but since logos, color, typography aren’t pages anymore we can link to the specific section if needed, for example: https://foundation.mozilla.org/docs/brand/brand-identity/color to https://foundation.mozilla.org/en/docs/design/branding/#color

- Yes, we should sunset the UI components page and when we link to /websites we can describe and link to the Figma components library when its ready

- https://foundation.mozilla.org/docs/brand/brand-identity/social-media/ should point to https://foundation.mozilla.org/en/docs/design/marketing/ _(link in description is missing /docs so goes to 404)_

- Trustworthy AI theme page: I think it could still be a useful brand expression reference in the future. It doesn't have to be its own page if it doesn't fit but can fold it into MoFo’s evolution of its brand expression somehow

- I haven't concluded if "Imagery" should be left as is or be called something else or if it and its child pages should be under branding structurally to simplify or not TBD but could be good to get some feedback on this

**Agency assets to Branding**
- Agency assets provided a good overview but is redundant with the content so pointing to a brand pages makes sense
- Related to how we frame "branding": I’m thinking if our “branding” page needs an overview/context that Design is more specifically referencing the visual expression elements of the identity when we say branding as it is generally quite broad _(like as described in what is branding page)_ if we are pointing external folks here.

**Comment by kristinashu** [comment]
Thank you so much Sabs! I've made all those updates with the exception of "Imagery" - perhaps we can discuss at crit.

**Comment by kristinashu** [comment]
Based on [this IA](https://www.figma.com/file/t8rWjvPG7Lfgkr3MkS8wiy/Documentation-IA?type=whiteboard&node-id=0%3A1&t=Qv6A7ZnPSYqFAIBx-1), I've updated the use of "imagery" to "graphics". I've also gone ahead and unpublished all the /brand pages and redirected them to the appropriate /design pages.

@sabrinang @beccaklam @nancyt1 we'll continue to iterate and improve on these page but for now this chunk of the work is done!
