### ISSUE TITLE
[QA] Navigation

### ISSUE THREAD

**Issue by nancyt1** [MozillaFoundation/Design#1187]
### Acceptance Criteria
**1. Audit & Research**
- [x] As a Mozilla designer I can find the process work in the Audit file

**2. Design**

_As a Mozilla designer I …_
- [ ] Build: can see that all colors, text styles, and spacing are using defined tokens where applicable
- [ ] States: can easily swap between states (On scroll, Open, Closed) and variants
- [ ] Responsiveness: can easily access all breakpoint states (Desktop, tablet, mobile) and resizing does not break the component
- [ ] Prototype: can easily use the component in a prototype with interactions already preset/hooked up
- [x] Accessibility: can see that all applicable a11y and localization standards (reference the checklist) have been met

**3. Documentation**

_As a Mozilla designer, I see that:_
- [x] All layers been named properly
- [ ] All variants and component properties have been named properly
- [x] The spec description explains function and editability
- [x] All editorial/content standards (ex. max characters, min/max width) have been defined
- [x] Variations have been listed
- [x] There are examples in context

_As a new Mozilla designer or contractor, I …_
- [x] Can easily discover the navigation component
- [ ] Can easily find this component using the asset finder using the MoFo Design’s naming conventions
- [x] Can easily understand what this component is, how to use it and what edits can be made to it

**Comment by nancyt1** [comment]
@sabrinang Hey Sabs! I finished the component and documentation, can you review whenever you have time? Or we can assign this ticket to someone else.

**Comment by sabrinang** [comment]
I reviewed and left some stickies in the doc
<img width="534" alt="image" src="https://github.com/MozillaFoundation/Design/assets/2492510/ad5b3188-8a74-4670-adc3-75db5ae64d6f">

I'll also type it out here so its easier to scan:

**Build**
- Colors: remove or used defined
- Size and positioning consistency:
   - Mobile: size and positioning changes in the prototyping animation (example: vertical shift motion in donate, vertical shift motion in menu + icon)
   - Tablet: (example: horizontal shift motion in donate and vertical shift motion in menu + icon)
   - Consider using a .base for consistency and also could be easier editing in the future if we need to swap out a logo
- Component height: component primary is 77px & zen is 79px (make both same height so when changed height is the same as its 78px on production for both) 
   - you can also use border bottom instead of a line if it helps

**States / Prototype**
- Hover states
    - secondary nav: hover and selected state should be black text (additional items appear in black though)
    - vertical nav: missing hover black text, position shifts, child page arrow disappear/reappear
    - mobile dropdown + tablet opened : missing hover states
    - tablet open/close icon transition preferable to mobile the sliding icon transition
    - Button: disappearing label, size shift

- OnScroll 
   - not functioning as described
   - scroll behaviour position is currently “scroll with parent” might need to be “sticky (stop at top edge)”
   - since it is the same component with different prototyping behaviour I think giving instructions how to prototype the desired effect instead of another variant could streamline the options

**Naming**
Consider adding nav to “Mobile Nav Dropdown” to distinguish it as a nav

**Variant combinations**
I think since some combinations doesn’t exist it changes when you select some combinations of variant properties and it switches:
- primary, desktop, menu open → zen desktop menu open
- primary mobile menu open → zen desktop menu open
- zen desktop opened → primary tablet opened 
- zen, tablet, default → primary, tablet, default
- zen, mobile, default → zen, desktop, default

**Ideas:**
Since zen mode only exists for desktop primary, consider something that is only disclosed when that option is selected so it isn’t a selectable options with other variants (could be a boolean option for desktop primary only). Possibly streamline “opened” and “open menu” to be the same thing or clarify name? it can be one less option overall as I think only “menu opened” only applies to zen so can appear for just that variant also.

**Editing nav items**
- do we need to describe about clicking into text if we want to encourage editing in right component panel?

**Fix long text**
- should this be set by default in the vertical nav to have the vertical nav links be set to fill? (is there a use case where we need the text to extend pass the vertical nav frame)

**Comment by nancyt1** [comment]
@sabrinang Thanks for your detailed feedback!!! I've fixed most of the feedback and I've added some stickies and comments in Figma with some more questions. For your zen mode idea, a boolean would be super helpful but I'm having trouble implementing it. Do you have capacity to troubleshoot with me?

**Comment by sabrinang** [comment]
Yes I can help troubleshoot next week! (we can also try other strategies if boolean doesn''t work in this scenario)

**Comment by sabrinang** [comment]
@nancyt1 Great work streamlining the positioning consistency and resolving how variant combinations are presented. It’s way more intuitive now and I can only make combinations that are available!


Some stuff I noticed this review:

**Secondary nav component height**
I don’t think users would ever swap secondaries and primaries but consider if secondary desktop/tablet should match primary desktop/tablet? _(77 vs 78, 77 vs 64)_


**Documentation**
In the documentation (not the component), the top two examples hover underline not along bottom edge and mobile nav has different stroke transition. In the documentation (not the component), mobile nav open also animates different and contains stroke when closed which is different from asset panel component.

**Hover/Animated states**
- Hover underline has gap between bottom edge
- Hover button stroke alignment
    - I notice on hover it visually shrinks size (even though same height since outside stroke alignment extends beyond container)
- Hover text shifts
    - I notice some links shift because it is changing in style?! 
        - Example: “This is really long text to test this component” in vertical desktop nav the “l”s starts with a curved stem and it disappears after being hovered but causes some shifts in the kerning 
    - Vertical nav child links
        - Maybe creating a child variant would help arrow not disappear on first hover state

These aren't blockers but some details to consider

**Comment by nancyt1** [comment]
Thanks Sabs! I updated these small details and published the components! I decided I'll revisit the vertical nav menu once we get to the default page templates.
