### ISSUE TITLE
[QA] Forms and Snippets

### ISSUE THREAD

**Issue by nancyt1** [MozillaFoundation/Design#1200]
### Acceptance Criteria
**1. Audit & Research**
- [x] As a Mozilla designer I can find the process work in the Audit file

**2. Design**

_As a Mozilla designer I …_
- [x] Build: can see that all colors, text styles, and spacing are using defined tokens where applicable
- [x] States: can easily swap between states and variants
- [x] Responsiveness: can easily access all breakpoint states (Desktop, tablet, mobile) and resizing does not break the component
- [x] Prototype: can easily use the component in a prototype with interactions already preset/hooked up
- [x] Accessibility: can see that all applicable a11y and localization standards (reference the checklist) have been met

**3. Documentation**

_As a Mozilla designer, I see that:_
- [x] All layers been named properly
- [x] All variants and component properties have been named properly
- [x] The spec description explains function and editability
- [x] All editorial/content standards (ex. max characters, min/max width) have been defined
- [x] Variations have been listed
- [x] There are examples in context

_As a new Mozilla designer or contractor, I …_
- [x] Can easily discover this component
- [x] Can easily find this component using the asset finder using the MoFo Design’s naming conventions
- [x] Can easily understand what this component is, how to use it and what edits can be made to it

### Publishing Procedures
1. Assign original designer to:
- [ ] Go to _Publish Library..._ and select relevant changes to publish and fill "Optional description of changes" and select _Publish_
- [ ] Comment and close this ticket when complete

**Comment by nancyt1** [comment]
This is ready for your review @sabrinang!

**Comment by sabrinang** [comment]
I left pink stickies in the figma pages and will summarize some review feedback here:

**Forms**
- Naming for themes: are we adding “mode” and instead of default using “light”? _(Note: this is different from what's used so far)_
- Form styles: there is a missing combination for light/default, horizontal _(it switches to dark, horizontal)_
- Form states: missing combination for expanded, light/default, horizontal _(switches to expanded, dark, horizontal)_
- Bases: I’m wondering if all the form components are bases or can be a component that shows up as well _(or consolidate callout form and footer form in one component, footer form also missing submitted state)_
- Pop background: I think that can live as a token style that is applied to any box rather than a base background? _(maybe token boxShadow popXlarge + borderWidth 1 could work etc.)_

**Snippets**
- Documentation text updates and use default instead of dark theme use in some areas _(looks like you already updated a few of these!)_
- Alignment of element with columns and use constraints for responsive behaviour
- Naming thoughts for newsletters and asides
- Petition form missing submitted state?

**Comment by sabrinang** [comment]
Went over reviews and everything is looking good. Two things to note:
- wait for FA stuff to stabilize so we can build that flow/pattern later, what we have is good for organisms right now
- naming conventions: not just for this component but we will consider how we name and organize light/dark versions in the future

@nancyt1 ready for you to publish

**Comment by nancyt1** [comment]
Thank you! Published this to library!
