### ISSUE TITLE
Digitize stickers for All Hands

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#1228]
Follow up from https://github.com/MozillaFoundation/Design/issues/1225 

Some todos
- [x] Get input from stakeholders
- [x] Digitize 3 directions
- [x] Share with stakeholders

**Comment by kristinashu** [comment]
I've shared the Figjam with Steph and Tarendeep for input!

**Comment by kristinashu** [comment]
Steph has asked the social committee to add hearts to their favs by eod Thurs July 13.

**Comment by kristinashu** [comment]
Will prep for print here https://github.com/MozillaFoundation/Design/issues/1236

**Comment by beccaklam** [comment]
I’ve exported the donut and snail for print in my [folder](https://drive.google.com/drive/folders/1AcbQS-yF7THt92Smif4TmSCqQ9veE7Ej?usp=sharing)! Not sure what printer the donut is using but I just prepped it the same way as the snail? CMYK and a cutline. Also did a 2 inch and 3 inch version since I’m not sure what size we’re going with for the donut either.
