### ISSUE TITLE
[Documentation] Wrap up design system work

### ISSUE THREAD

**Issue by nancyt1** [MozillaFoundation/Design#1229]
- [x] Documentation in /design, maybe confluence
- [x] Clean up roadmap
- [x] Clean up so in a shareable state
- [x] Clean up naming/semantics
- [x] Move audit work to new file?

**Comment by sabrinang** [comment]
- cleaned up [WIP] Component Library file
  - opened share settings 
  - removed empty/unpublished/placeholder pages _(Illustrations, Banner Page, Default Page, Publications & Article Pages, Streamfield Blocks)_
  - moved notes/archive to [Archive](https://www.figma.com/file/EMjtNMAz1xurM5CBiHzptz/Archive?type=design&node-id=0%3A1&mode=design&t=XNarctjHZkbi8M7U-1) file

**Comment by sabrinang** [comment]
Took a pass at organizing the delivery plan https://github.com/orgs/MozillaFoundation/projects/7/views/2 but would be good to chat about what to cut down as we don't have time/capacity to continue DS as we have.

**Comment by sabrinang** [comment]
**regarding moving Audit/Research to new file**

We've discussed that since we are still in the crafting process we can leave the content in context of the work but have it a located a bit more separate on the same page for now. Also, the file isn't large with 5% memory usage so it should not effect performance/load time.
<img width="300" alt="image" src="https://github.com/MozillaFoundation/Design/assets/2492510/b7c40de0-fe29-450c-b932-652e81131596">

Our plan for the future is we could move this to a dedicated Audit/Research file but is currently not necessary.

**Comment by sabrinang** [comment]
we've organized the delivery plan in groups across sprint but it is flexible to rearrange according to how much capacity we have

**Comment by sabrinang** [comment]
**regarding Shareable State**

Files have been cleaned up (templates separated in file and archive file) and share settings opened and have been shared to others _(i.e. take home test for designers)_

**Comment by sabrinang** [comment]
**regarding Naming**

We created a ticketed dedicated to thinking about naming conventions and to document that as guidelines here https://github.com/MozillaFoundation/Design/issues/1232

**Comment by sabrinang** [comment]
**regarding Documentation in /design and confluence**

We published our DS documentation and links on https://foundation.mozilla.org/en/docs/design/design-system/.
We also included this in our internal confluence documentation as a child page from the design team page on https://mozilla-hub.atlassian.net/wiki/spaces/FOUNDATION/pages/313720930/MoFo+Design+System
