### ISSUE TITLE
Finalize stickers for All Hands

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#1236]
Social Committee
- [x] Get approval from stakeholders
- [x] Decide on printer https://www.jukeboxprint.com/
- [x] Prep for printer 

Insights
- [x] Get approval from stakeholders
- [x] Decide on printer
- [x] Prep for printer https://stickerapp.com/support/how-to/how-to-prepare-your-file-to-print-with-stickerapp

**Comment by beccaklam** [comment]
I’ve exported the bagel and snail for print in my [folder](https://drive.google.com/drive/folders/1AcbQS-yF7THt92Smif4TmSCqQ9veE7Ej?usp=sharing)! Not sure what printer the bagel is using but I just prepped it the same way as the snail? CMYK and a cutline. Also did a 2 inch and 3 inch version since I’m not sure what size we’re going with for the bagel either.

**Comment by kristinashu** [comment]
Thank you Becca! Nancy can review the bagel once we know the specs.

**Comment by kristinashu** [comment]
@nancyt1 Social committee will use Jukebox for printing

**Comment by nancyt1** [comment]
These were exported and stakeholders were notified!
