### ISSUE TITLE
Plan training / share for How to Make a Moodboard

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/Design#142]
It concerns me that only one person on our team had ever made a moodboard from scratch before, and that no one seemed to have a good handle on how to approach a brand from scratch. Let's do some training, sharing and talking so we can all develop this skill set.

cc: @cassiemc @kristinashu @sabrinang @natalieworth @flukeout @lovegushwa @vazquez

**Comment by cassiemc** [comment]
Might be able to get someone external to demo their process.

**Comment by lovegushwa** [comment]
@cassiemc I have created different things like moodboards, it could be something as loose as a giant wall with pinned up images and sticky notes to categorize benchmarks (good luck doing something like that at since we are decentralized) or as formal as a really tight deck that communicates specific attributes. The latter is probably closer to what we need. But this is for us and not a client so I think that's an important distinction. 

I could outline a process / steps for developing a brand. I think the key is to start small on a number of hypothetical bits that cover a broad range of design problems and work iterativly. The tricky part is carving out some time to do this, and it should be fun.

**Comment by cassiemc** [comment]
I should clarify, I have done this process many times. I think even just sharing some benchmarks would be super valuable, and I also like the process you outline @lovegushwa. Maybe you and I can collaborate on this as a p2 this heartbeat?

**Comment by lovegushwa** [comment]
@cassiemc yes let's collaborate on this!
