### ISSUE TITLE
Test colour palette with web lit map

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/Design#152]
Test @kristinashu's new colour palette with one of your typical use cases. 

Use this palette: https://redpen.io/aq798f74c9a3ad7266

If you feel the need to make further adjustments to the colours, you can use @flukeout's tint generator here: http://flukeout.github.io/color-generator/ but please do document what changes you made and why.

Let me or @kristinashu know if you have any questions!

**Comment by sabrinang** [comment]
![web-literacy_colour-test](https://cloud.githubusercontent.com/assets/2492510/13589741/03d74408-e48f-11e5-95dd-6e25e460be62.png)
This is an initial test without introducing new shades/tints to the palette, next iteration is to adjust the variations of grey.

**Comment by sabrinang** [comment]
![web-literacy_colour-test2](https://cloud.githubusercontent.com/assets/2492510/13680240/908c6d14-e6ac-11e5-992e-42911bd5faba.png)
The 50% grey was a bit heavy on the page so I prefer the 55% grey (#E3E3E4) for literacy sections

**Comment by sabrinang** [comment]
To avoiding conflicting grey issues in colour blindness, I tested two more palettes avoiding light greens and light reds that produced grey tones:
![web-literacy_colour-test3](https://cloud.githubusercontent.com/assets/2492510/13709948/63238244-e76b-11e5-9ef9-07fe2b63125c.png)

![web-literacy_colour-test4](https://cloud.githubusercontent.com/assets/2492510/13685146/e67d9d80-e6c3-11e5-9356-03a4b0a3194e.png)
![web-literacy_colour-test5](https://cloud.githubusercontent.com/assets/2492510/13685147/e8f99cee-e6c3-11e5-95e8-71f43e255a21.png)
![web-literacy_colour-test6](https://cloud.githubusercontent.com/assets/2492510/13709960/6ddec32e-e76b-11e5-9ff3-0831b14cda81.png)

Overall, these three palettes provide contrast with the greys. The second palette may be the most effective since we don't use red on the teach site (seen in palette 1) and red might be associated to other meanings (as surfaced in the survey to avoid red or green which are tied to various meanings) and we do not reuse the light blue colour (seen in palette 1 & 3) which is currently used to indicate links.

**Comment by kristinashu** [comment]
Thanks @sabrinang! So your only recommendation is to update the 50% grey to 55% grey (#E3E3E4)? Otherwise, you are comfortable with using the palette for the web lit map?

**Comment by sabrinang** [comment]
@kristinashu Yup, the colours are fine and prefer that extra grey shade of 55% lightness since it looks more subtle for background use (I don't think I'd update 50% to 55% for the palette but have an option of shade in between). If it seems odd to just have one shade with an odd percentage or if this is introducing too many shades I can go back to use 50%.

**Comment by sabrinang** [comment]
Will be using this palette of colours to implement on the web lit map.
![web-literacy_colours](https://cloud.githubusercontent.com/assets/2492510/13755409/5d85bc70-e9d8-11e5-9a93-2d7de3e35dc3.png)
