### ISSUE TITLE
Refine and communicate info architecture plan

### ISSUE THREAD

**Issue by xmatthewx** [MozillaFoundation/Design#158]
@kristinashu wrote a [nice summary](https://github.com/MozillaFoundation/plan/issues/764#issuecomment-201051122) on next steps on the information architecture plan. 

I would add to that: find a way to document and communicate the plan that will help ensure everyone knows and follows it. For example: could the Phase 1 diagram live on https://www.mozilla.org/en-US/foundation/? Might be a challenge to land that, but it would be more accessible and useful than hidden in a doc. 

It will help us migrate current assets and wrangle new projects as they emerge: 
 - Need a site for an initiative? Where does it live on this diagram? 
 - Many initiatives will be better served as a page on site with traffic, than as a new standalone site.  
 - Doesn't fit on the diagram? We risk diluting brand and diluting resources. We shouldn't build it. 

@kristinashu  @hannahkane - How can we best document and communicate this plan?

**Comment by hannahkane** [comment]
Maybe this belongs in https://book.mozillafoundation.org/? cc @OpenMatt

**Comment by kristinashu** [comment]
@xmatthewx @hannahkane did we talk about this one specifically?

I'm not sure this should live anywhere quite yet. It seems like it will be in flux for the next while. But https://book.mozillafoundation.org/ does seem like a logical spot if we do put it up.

We have tickets for Phase 1 of Phase 1 and I'm optimistic that once the first steps have been implemented the rest will follow suite. It shouldn't be something we have to 'enforce' but rather something people will want to follow because using the IA and url conventions will give them more exposure...

**Comment by hannahkane** [comment]
It might be good to just make sure the diagram is updated for now. I added a question to https://github.com/MozillaFoundation/plan/issues/764 about whether Women and Web Lit was left out as an oversight. Would also like to have it capture our thoughts about Curriculum and Leadership being horizontals across the hub verticals.

**Comment by xmatthewx** [comment]
Cool. Cool. Does this diagram live in google drive? Let's make a mzl.la shortlink a folder of the latest so we can always find it. 

We might add spots on the diagram to represent where new things will be added. 

For example, we could have a box with a dotted outline labeled `New Hub` to show where those will land. (Personally, I would only put established Hubs like Science on the diagram, not new experimental ones.) 

There could a dotted box as subpage of Learning labeled `New initiative` to clarify where smaller endeavors might appear.

**Comment by kristinashu** [comment]
@xmatthewx @hannahkane @sabrinang let me know if this is helpful: https://goo.gl/4Mm718
I've updated the first slide: 
- embedded leadership and research into the different hubs
- added women & web lit
- set aside news (because they're more independent) and fundraising (because it is sort of moco)
It's pretty busy looking but I wanted to include examples like Gigabit, blogs, reports...

**Comment by kristinashu** [comment]
Also updating the spreadsheet version https://goo.gl/UKjxNl

**Comment by xmatthewx** [comment]
👍 Looks good. I added a couple of comments. Nothing major. 

Is there an advantage to spreadsheet vs slide? If so, cool. If not, let's just maintain one doc moving forward for easiness. http://bit.ly/MoFo-IA

**Comment by kristinashu** [comment]
Thanks for the comments, I've made a couple updates to the slide. 

I find the speadsheet easier to update but think slides might be better for outsiders to look at so lets only move forward with the slides.

**Comment by kristinashu** [comment]
Is this good to close?

**Comment by xmatthewx** [comment]
Yes? I think a link to this diagram needs a home. In absence of better options, maybe the readme of this repo? A nod towward: http://bit.ly/MoFo-IA

**Comment by kristinashu** [comment]
Oooh my first readme edit! I've added a blurb and link to the chart: https://github.com/MozillaFoundation/Design/blob/master/README.md Feel free to edit.

**Comment by xmatthewx** [comment]
😄
