### ISSUE TITLE
[MoFo Unified Design] develop a distribution and versioning strategy for the sketch file

### ISSUE THREAD

**Issue by simonwex** [MozillaFoundation/Design#178]
It's the hope that the unified design work will be of use to staff as well as community designers and developers. As we evolve the assets, being clear as to which version of the sketch file is being used will be key so that people aren't designing with outdated standards. 

Once it's ready for the community, we'll also need to host the file somewhere that is accessible and makes sense.

**Comment by simonwex** [comment]
A few thoughts:
 * version the sketch file with a symbol and watermark it on each page
 * include the "last updated" date as part of the watermark
 * distribute the sketch file in the onesie repo
 * include the download link in a welcome message for an email distribution list so we have a mechanism for updating users

**Comment by simonwex** [comment]
@kristinashu @sabrinang @gvn any thoughts?

**Comment by xmatthewx** [comment]
+1 to versioning with a date in the file name and as a symbol that appears prominently.

We should continue to store and share the file in a public Google Drive folder with the rest of the design assets, at least until the work stabilizes and we discover a need to change that practice. We can invite people to the existing design team list (and dev list?), and to chat. Let's not create another channel unless we discover a need for it.

**Comment by kristinashu** [comment]
I spoke with a moco designer and they use Git for version control of Sketch files. I really like this idea, at least internally for design and dev. 

Since Sketch auto-saves, it could get problematic using Drive/Dropbox if we have multiple people open the same Sketch file at the same time. Also, since we would need to push our updated Sketch file, it would make sure we're only sharing 'final' files and not a WIP that auto-saved.

Since we would have to add a comment to the commit, it would force us to explicitly say what the changes are.

We would all get notifications when a commit has been merged so we would all know we need to update.

Git would be able to handle merge conflicts but at least will be aware that version-splitting has happened and we could compare manually.

For the community, it would be a great way for them to contribute to the Toolkit in a controlled way.

My only concern would be for staff and community members who aren't comfortable with Github. But perhaps we have a download link in the Readme or maybe we could make some script that would automatically update the latest merged file to a read only Drive/Dropbox folder which everyone would have access to.

Let me know what you think and I could set it up, test it and get feedback.

**Comment by flukeout** [comment]
+1 This sounds cool. We could also create and host a small gh-pages site on that same repo aimed at contributors and people who want to use our toolkits & assets.

**Comment by xmatthewx** [comment]
Sounds like a plan Kristina. All the reasoning sounds good to me. I have two concerns I'd like us to consider: 
 - We tell new designers and program people that they can find everything they need in the Design Assets Google Drive folder. How can we bridge a connection between this and that?
 - Where does this live? If the UI toolkit contains elements that could be used to design email newsletters,  integration with third party tools, etc, does it live in the design repo or does onesie expand to become more than a bootstrap theme?

A benchmark for a github page: https://standards.usa.gov/

**Comment by kristinashu** [comment]
I'm reluctant to create yet another repo but it might make sense to have a Unified Design Style repo. Using Luke's idea of the github pages, it could house the User Guide, UI Toolkit and the Resources/Assets. Onesie would have to be a separate repo but it would have a slightly different audience so that might be ok. If the github pages are user friendly enough then we wouldn't necessarily need a Drive folder.

**Comment by xmatthewx** [comment]
Agreed. We might be able to achieve what you want, without creating a new repo. We aren't using gh-pages in this repo yet, and mozillafoundation.github.io/design would be a good onestop home for all of our things. We could recover some of the content we formerly had in build dot webmaker. I think we'd still need gdrive for project files and archives (though maybe not). Regardless, I'm game to build out a home for our evergreen assets.

**Comment by kristinashu** [comment]
I'm leaning towards separating the Unified Design Styles type work from our regular design work to avoid any confusion. This way the Unified Design Styles repo would only have commits for the UI Toolkit, the readme or pages would only reference the User Guide/UI Toolkit/Resources/Assets, and issues would only be relevant to the unified style. Whereas our design repo would just be about general design issues that aren't related to the Unified Design Style.

I think the rest of our project files, created from the Toolkit or not, would still need to be in Drive and issues would be in their respective repos. I see the Unified Design Style work as being different from the rest of our project work since a lot more people will be working on it and using it. Compared to something like the science site were there's really only one designer and version control and sharing the files is slightly less important.

But maybe not, I'm open to suggestions here. @sabrinang any thoughts?
