### ISSUE TITLE
Identity for an initiative

### ISSUE THREAD

**Issue by xmatthewx** [MozillaFoundation/Design#192]
Do any of you have a good example of a logo or treatment for a not-totally-official Mozilla initiative? We need a good benchmark while we wait for the Mozilla rebrand.
### Issue

Almost once per week, someone on staff requests a logo for an initiative, a staff-led thing within a hub or locale that isn't an official program or campaign that appears on the strategic plan. I'm not talking about official programs (science, clubs, ...) and campaigns.

We could save a lot of time and discussion if we had a single example of how to handle these things while we wait for the Mozilla rebrand. How would you associate a thing with Mozilla without creating a formal connection?

cc: @hannahkane @kristinashu @sabrinang @natalieworth @flukeout @lovegushwa

**Comment by sabrinang** [comment]
I am wondering would a minimum requirement be to incorporate the official mozilla wordmark or not? since it is the main visual method to associate a thing with Mozilla but on this also feels like this makes it formal too...

An idea could be to make it clear how it is related to mozilla, albeit boring and blunt here is an example: 
<img width="1167" alt="screen shot 2016-07-14 at 10 14 58 am" src="https://cloud.githubusercontent.com/assets/2492510/16848736/10f80f32-49ac-11e6-815e-49b44908913f.png">
This isn't very visual and wouldn't work well on small applications so I'll keep in mind to look for another single example or an alternative for a one-style fits all solution if I come across any but keeping it simple as we wait for the Mozilla rebrand. 

Note: A bunch of contributions for "not-totally-official Mozilla initiative" treatments could be found in the community design repo: https://github.com/mozilla/OpenDesign/issues?q=is%3Aissue+is%3Aclosed

**Comment by flukeout** [comment]
I like this approach @sabrinang. A variant of this would be to create something non-editable like the badges that app stores use...

![image](https://cloud.githubusercontent.com/assets/25212/16857569/733b29e4-49d5-11e6-8b7e-ab133689365f.png)

We could have a few color & copy options, but they would just be included somewhere on the project page as-is.

**Comment by xmatthewx** [comment]
This is all good thinking. With the right visual/aesthetic distance, we can show association without making big promises or needing to evaluate every last endeavor by a hive, club, or hub.

Other phrases: Supported by ... Powered by ... in Partnership with ... something vague and flexible that won't concern legal. How about ... "Part of the **Mozilla Network**"

**Comment by flukeout** [comment]
Here are some quick 'badge' ideas...

![image](https://cloud.githubusercontent.com/assets/25212/16858568/a99ba188-49dc-11e6-98b7-665eb707de96.png)

**Comment by flukeout** [comment]
Anyway, as @sabrinang and I just discussed, we really need to think about the wording here.

* Should we reference the Foundation or the Mozilla Learning Network?
  * Just "mozilla" seems too MoCo
* Do we want different badges to correspond to different tiers & types of support?
  * That would make the wording easier to figure out, as it would be more specific.

**Comment by flukeout** [comment]
It's already proving useful...

![image](https://cloud.githubusercontent.com/assets/25212/16859170/7b118c9c-49e1-11e6-8b65-d1a395b40db6.png)

**Comment by xmatthewx** [comment]
Awwww. ❤️ ♨️ heart melts. 

`mozilla community project` nails it. Clear and flexible. I like the first one, top left. Plain and simple. I also like the trendy one for when we need to spell out the relationship.

**Comment by xmatthewx** [comment]
@ldecoursy & Meghan. We'd love to get feedback from the affiliate policy group. 

Please note: our goal is to
 - unblock staff initiatives by reducing production roadblocks
 - iterate today a more unified identity under Mozilla
 - create a simple, temporary solution while we wait for the Mozilla wide rebrand

This simple, easy, unified approach won't solve all the problems of our fractured identify, but it's preferable to the status quo and achievable alternatives. 

Is Meghan on Github? I could find a handle in Github or on Phonebook.

**Comment by hannahkane** [comment]
cc @mcdermott415

**Comment by mcdermott415** [comment]
Thanks Hannah. What does this mean? I don't use it but need to start. Sigh.
Best way to start?

**Comment by xmatthewx** [comment]
`Pause button` ✋ . Given complexity of "affiliate relationships", group seems to think we should wait for rebrand.

**Comment by flukeout** [comment]
![image](https://cloud.githubusercontent.com/assets/25212/17065693/1a0b2b3e-4ff8-11e6-98f3-aca238cacc59.png)
