### ISSUE TITLE
 [Hawaii All-Hands 2016] Network Audience Groups

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/Design#217]
We are digging through research and documentation on our existing audience to curate a collection of members that represent our network.

#### Research Sources:
- 50 members of MLN recognition program (7 network member profiles from Rizwan)
- 12 members of the MLN advisory committee (spreadsheet from Rizwan)
- 5 MLN member types: Professional, Emerging Leader, Young Leader, Executive & Champion) (leadership board slides)
- member’s stories on StoryEngine (from consultant Christine)
- 5 types of Conscious Choosers profiles from Mozilla market research (idea couture slides)
- MLN (internal) persona writeups from London 2016 (link from Simon)  

So far we are thinking about having a few members archetypes that represent various areas of engagement. We have a variety of exemplar members as well as members on the fringe or outside of the network - here is a rough diagram:

![network-audience-levels_draft](https://cloud.githubusercontent.com/assets/2492510/20451294/776f023e-adac-11e6-912a-7e7fc476b9c5.png)

The member terms are inspired from the research sources but are still tbd.

As we continue, we will see if these people represent that network, understand why we select the profiles, who we might be missing and more that will inform our all-hands activities. Additional details are captured the in presence proposal here: https://docs.google.com/document/d/1p01zYPQ0woSphzvpOfE-riV5RyaMwR4xjaLhsAtTEZk/edit#heading=h.5qb28hsjevfl 

cc: @xmatthewx @taisdesouzalessa @hannahkane @simonwex @chrislarry33

**Comment by taisdesouzalessa** [comment]
Here is a WordCloud map of part of this audience, based on data we had or that is available online. I think the WordCloud can give us a big picture of things the audience care about and helps us to decide about the member archetypes we should select.

1.  7 network member profiles from Rizwan - from the 50 members of MLN
<img width="1007" alt="screen shot 2016-11-18 at 5 01 38 pm" src="https://cloud.githubusercontent.com/assets/22157921/20451590/3279606c-adb0-11e6-922f-47b3d8d3108c.png">

2. 12 members of the MLN advisory committee (spreadsheet from Rizwan)
<img width="1022" alt="screen shot 2016-11-18 at 4 00 08 pm" src="https://cloud.githubusercontent.com/assets/22157921/20451658/dd43780c-adb0-11e6-85c2-69e4f534adfe.png">

3. member’s stories on StoryEngine (from consultant Christine)
<img width="1114" alt="screen shot 2016-11-18 at 4 58 10 pm" src="https://cloud.githubusercontent.com/assets/22157921/20451664/0023294e-adb1-11e6-8073-09d330e01369.png">


ANALYSIS:
- There are similarities between groups 1 and 3 which could indicate the groups are similar. I think it is a safe assumption to say that the Story Engine users are represented in bullet point #1 (7 network members).
- The 12 members of the MLN advisory have very strong keywords related to technology and work.
- I took a look at the [Klout score](https://klout.com/corp/score) just to understand the influence of the groups 1 and 2 in social media and I got an average of  39.6 for group 1 and 44.1 for group 2. This is more a curiosity and it should be taken with a grain of salt because I think their influence is measured way beyond social media and those numbers are just averages. But is is interesting (and expected) that the MLN advisory members have a stronger social media influence.

**Comment by taisdesouzalessa** [comment]
Here is a spreadsheet with the MLN Member Archetypes, based on the categories defined in this ticket. I have some questions there (please see the doc to see my comments/questions). This spreadsheet still has some gaps (I'll keep working on that together with Sabrina) and I think we are on the process to define a good starting point for discussions about the target Member Archetypes and its goals for this first stage of the MLN we presence.

https://docs.google.com/a/mozilla.com/spreadsheets/d/1hmunwMP5CX-wYPVpTswdlZDW7TPHc2WnGF6qdzh9ob4/edit?usp=sharing

Would love to hear your thoughts, comments, what's missing, opportunities for improvement.

**Comment by taisdesouzalessa** [comment]
Here is an activity that @sabrinang  and I drafted for our All Hands. This is be a handout.
The goal of this activity is to learn:
1. If the audience groups' summary is correct 
2. What are the top 3 audience groups we should focus
3. If the audience buckets are correct
4. Goals, challenges of the top 3 audience groups and how we can help them
5. If we see any opportunity of group movement in terms of engagement

![persona-activity](https://cloud.githubusercontent.com/assets/22157921/20724923/05fdd220-b625-11e6-8178-29b1335c42b1.png)

The numbers represent the copy we will place. The document with the copy is here - feel free to add your contributions there:
https://docs.google.com/a/mozilla.com/document/d/1OPQBQsY4S8qAh13Y_wOkeLagdQJfQIAyRLqcqoFNYDw/edit?usp=sharing

@xmatthewx @hannahkane - we would love your input there so we can tweak this document before doing the final version and do the test-drive in our office.

**Comment by xmatthewx** [comment]
A lot of this looks great. Look for opportunities to reduce complexity, and reduce the need for detailed instructions. Try and paper prototype the ideas with co-workers in the office before you even worry about the design of this document.

**Comment by hannahkane** [comment]
Added my two cents to the document. Nice job. Looking forward to learning how the test-drive goes.

**Comment by taisdesouzalessa** [comment]
**Update:**
We decided as a team to stay away from the activity posted above and instead have a sheet that facilitates our conversation with staff. This new approach will give us more valuable outcomes.

Here is a short description of the new approach as I understood so far:
https://docs.google.com/a/mozilla.com/document/d/1Fq3M7_5nP9HgmBC2CeUG_nEFeEMr2ajc6xihRgkYMzo/edit?usp=sharing

I'll have the final audience groups sheet by Friday and I'll print them out so we can talk about them during All Hands.

@hannahkane @flukeout @xmatthewx @kristinashu - could please take a look at the doc and give your input? Our plan is to get audience's and staff's insights that will guide our website design later on.

**Comment by taisdesouzalessa** [comment]
Here is the deliverable for discussion in our All Hands:

https://drive.google.com/a/mozilla.com/file/d/0B3b1KWRwjxtoMkpiTUsxTDY4ZTg/view?usp=sharing
