### ISSUE TITLE
IMLS Video Moodboard & Style Guidance

### ISSUE THREAD

**Issue by flukeout** [MozillaFoundation/Design#228]
Chad and An-me are coordinating with a production house to film some web literacy videos at the end of this month. To aid in this effort, the video contractors have requested some help with style guidance. I'm still waiting for the details of what kinds of screen treatments they'll be creating, but I'm guessing there will be some introduction screens, transitions, name overlays, etc.

In addition, they'll be creating some physical props (like a giant cube of HTML tags) so we might want to advise on that stuff too.

I was thinking that we could offer them a few things...

* Google presentation deck with some of the most recent work @sabrinang has been doing in adapting the new mozilla identity, including color swathes
* The following assets
  * New mozilla logo
  * The new fonts (zilla, and the new slab + open sans for body copy)
* Check-ins via video while they're producing this work to make sure everything is looking fly and on point

cc @xmatthewx @sabrinang How close are we to something that you feel comfortable sharing with them in this context. I think given their timeline, they'll want something by early to mid February.

**Comment by xmatthewx** [comment]
Cool. A few thoughts and things: 

1) **Assets & Guideline**: There will be a site shared this week with the logo and work-in-progress brand guidelines. Let's always point people there for logo, type, colors. 

1) **Site style**: We will update our deck for orienting staff to the new site with our latest site comps. We can point them to that. Let's not create something specific for this initiative to reverse engineer this site into a more general style guide. Site could evolve as brand rolls out.  

1) **Video style guidance**: Are they in touch with Zannah and her video work? Might also be good to loop in Jordan and advocacy and have a single opinion on videos, title screens, etc ... things that aren't campaign specific. Rather than investing in custom work for this specific initiative. 

Do these opinions make sense to you @flukeout @sabrinang??  

cc @hannahkane

**Comment by flukeout** [comment]
@xmatthewx Yeah, sounds good. I'll check in with advocacy to see how the video stuff is progressing. Once the **Site style** deck is updated, I'll send it along.

**Comment by kristinashu** [comment]
Closing this but please reopen if needed.
