### ISSUE TITLE
Advocacy -> Network user journey example

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/Design#232]
As discussed, we'd like to create a set of possible user journeys describing the user experience interacting with Advocacy content (videos, petitions, blog content, etc.) and Network content (opportunities, site/blog content, events, etc.), including the pathways between this content.

Our idea is to create a set of draft user journeys leading up to All Hands, and then use face time to share, discuss, and synthesize these journeys.

To start....could we work on a single example of a user journey?

cc @taisdesouzalessa @xmatthewx @lovegushwa

**Comment by taisdesouzalessa** [comment]
Yay! I love this idea, Hannah. 

I was wondering if you think it would be useful to do 2 journeys: one from advocacy side and one from network so we can see where they overlap and how we would stitch them together? Not sure if this will make things more complex than it should.

For the Network side, we have a lot of data from our users, based on previous research. I think it is very important we ground those maps in research as much as we can to make sure our maps reflect real user experiences since we will use them as artifacts for decision making in the future.

- Master list with existing research from Network audience [here](https://docs.google.com/a/mozilla.com/document/d/1TvdQJdXgNunuw9fKpov-bD048-HdmW5w_DS4BEnyCII/edit?usp=sharing).

- Spreadsheet highlighting the users that are in the Network site and also in the Story Engine [here](https://docs.google.com/a/mozilla.com/spreadsheets/d/1U7n-ofmhh51XZes4m-BAnPNlGyPamgkCI01STneRRto/edit?usp=sharing). Those stores are very insightful in terms of different users needs and their journeys with Mozilla.

**Comment by taisdesouzalessa** [comment]
@hannahkane just to make sure I understood correctly: would you like us to work in a user journey before All Hands (as an example) or should we prepare the tools we need to work in a single journey together with staff during All Hands?

**Comment by hannahkane** [comment]
hey @taisdesouzalessa - thanks for pinging on this. I think we need to hold off on this for a little bit. I need to gather more information before we get started.

**Comment by taisdesouzalessa** [comment]
@hannahkane as per our last talk, I put together a skeleton of the process and a spreadsheet with questions that could be useful to our user journey exercise. I also did a prototype of a survey (I shared that with you) so you can see how it would work, from a staff standpoint. 

I would love your input! Please comment and edit as you see fit. Here is the doc: https://docs.google.com/a/mozilla.com/document/d/1Nvj0UgrTTKcH484ia1gmNd26Ml-u_ct2Pb3o-2HUX_Y/edit?usp=sharing

**Comment by hannahkane** [comment]
Thanks, @taisdesouzalessa! I added some comments. The spreadsheet questions are great; but I wasn't sure if they were supposed to correspond directly to the skeleton or not.

Would love @xmatthewx's thoughts when he has a moment. :)

**Comment by xmatthewx** [comment]
A few quick thoughts: 
 - Could story engine be used as an input for this? mofo and many orgs ask a lot of people, without always giving something back. with network engagement plan, we might not have bandwidth for more surveys and discussion. 
 - We should make sure that @taisdesouzalessa and others are included on any engagement focus groups. Some of this will be in plan with 270. Some will be imbedded with program community calls. We should make sure to ask Sam D, Lindsey, etc if they can invite us to attend to observe.
 - When we map, I have a preference to favor simplicity or comprehensiveness. This allows us to iterate. And could lead to an asset that is more likely to be used. 
 - Naive question: is some of this easier to map after the site is launched. If we ask someone today how they learned about mozfest or a network project for collaboration, we'll likely get a very different answer than we'll get if we ask in September.

**Comment by hannahkane** [comment]
Really good thoughts @xmatthewx. +1 to simplicity over comprehensiveness. Let's not spin our wheels too hard on something that is emergent.

Love the idea of using Story Engine in lieu of asking more of our members. And agreed that this process can be defined now, but we should expect it to get filled in post-launch. (See "emergent needs" above.)

Good call on making sure our design team is involved in focus groups. I'll put out some feelers around that.

**Comment by taisdesouzalessa** [comment]
• Love the idea of using the Story Engine too! There are a bunch of good insights there that can guide us at this first moment. 

• I really would like to be involved in the focus groups and community calls as an observer. I bet other designers would love too :).

• +1 to simplicity. I still think we can have a simple designed map though...could we explore options together once we get to this stage? 

• I think this is a great insight, Matthew! I can see the value of this tool if we had it ready at early stages of the site. At the point we are at the moment, I agree with you it is more valuable to do once it is launched. 
I like Hannah's suggestion to define the process now (since we have all the pieces of the site and questions fresh in our memory). We could also test the process with ourselves (I think you suggested this somewhere, @hannahkane) later on to see how we feel about it and what to refine.

**Comment by taisdesouzalessa** [comment]
@hannahkane @xmatthewx - here is the link for a mini presentation about the process (I was thinking about using that in our meeting on Monday, what do you think?): 
https://docs.google.com/a/mozilla.com/presentation/d/1sz9oSwZzNY3GD3-wdMickYAGn_kvd56dI7jbNQlBM5I/edit?usp=sharing

I still have to insert some visuals and I would love your input there before I do that. Let me know your thoughts on it.

**Comment by hannahkane** [comment]
@taisdesouzalessa - thanks for this! I think this will be helpful in our discussion on Monday. I only added one comment to the doc.

**Comment by taisdesouzalessa** [comment]
Work in progress - this work is being defined o this doc:
https://docs.google.com/a/mozilla.com/document/d/14btndV3QqDbmQ0_SYXQh8SDvwiozz3A7FMKX82yeDHg/edit?usp=sharing

**Comment by beccaklam** [comment]
Closing this as this journey doesn't seem applicable anymore with the new foundation site.
