### ISSUE TITLE
[MoFo Unified Design] Header and navigation

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#241]
From epic https://github.com/mozilla/network/issues/582, [alignment slide deck](https://docs.google.com/a/mozilla.com/presentation/d/1R1r4RCfoxKYAPVZerAPItJk1JZuALrc5jWm0t1QMijU/edit?usp=sharing) and related to previous alignment work https://github.com/MozillaFoundation/Design/issues/163

<img width="806" alt="screen shot 2017-09-18 at 1 13 06 pm" src="https://user-images.githubusercontent.com/1068783/30566133-a0f07468-9c7f-11e7-9f10-48b0446bea19.png">
<img width="764" alt="screen shot 2017-09-18 at 1 20 16 pm" src="https://user-images.githubusercontent.com/1068783/30566134-a0fff9b0-9c7f-11e7-94da-358f0de556d1.png">
<img width="766" alt="screen shot 2017-09-18 at 1 22 31 pm" src="https://user-images.githubusercontent.com/1068783/30566131-a0ec1bb6-9c7f-11e7-8b86-32a3f5705a14.png">
<img width="761" alt="screen shot 2017-09-18 at 1 23 23 pm" src="https://user-images.githubusercontent.com/1068783/30566132-a0eebbaa-9c7f-11e7-9910-bcaa044ee95a.png">

Highlights/things to consider from above:
- Logo turns to m on mobile
- Side menu on mobile 
- Animate transitions
- Black and white
- Menu icon
- Social icons
- Fit long menu items
- CTA buttons
- Back logo on two lines
- Language picker 
- Search
- Set nav height
(suggestion: have key items visible and then hide non-key ones in hamburger as screen widths become narrower)

Nice examples:
- https://www.swellinvesting.com/homepage
- https://codepen.io/chriscoyier/pen/bppOVP
- https://medium.com/@kollinz/hamburger-menu-alternatives-for-mobile-navigation-a3a3beb555b8 (like the progressively collapsing menu)

cc @sabrinang @taisdesouzalessa

**Comment by kristinashu** [comment]
@sabrinang @taisdesouzalessa here's what I'm thinking for the nav. Let me if you have any feedback!

<img width="479" alt="screen shot 2017-10-06 at 4 45 39 pm" src="https://user-images.githubusercontent.com/1068783/31302363-20575ad4-aab6-11e7-931a-81c01fc4ee22.png">

<img width="544" alt="screen shot 2017-10-06 at 4 47 41 pm" src="https://user-images.githubusercontent.com/1068783/31302364-208d50d0-aab6-11e7-9a10-5cbce19c8a2b.png">

**Comment by taisdesouzalessa** [comment]
I think those look great, Kristina. They look unified across properties and I like the stacked treatment in the  "Nav med". Nice approach to remove clutter. 

In the Network site menu, are you thinking about using a sans serif instead of Zilla?

For the mobile nav, I was wondering if it would make more sense to have the "sign up" inside the menu so the top looks cleaner (and for the network site users, once they sign up once, they don't need to see such a prominent sign up button on the home page). However, this approach introduces the complexity of doing the same for Pulse and maybe the "+" button is not clear enough by itself inside the menu...not sure.

Here is an example to illustrate this suggestion (expanded menu view):
<img width="327" alt="image" src="https://user-images.githubusercontent.com/22157921/31401351-7b32ced6-ada7-11e7-9b6b-ca98d7465138.png">

**Comment by natalieworth** [comment]
Assigning myself in this tic for reference.
