### ISSUE TITLE
[Design for Fellows & Awards at MozFest] Posters

### ISSUE THREAD

**Issue by taisdesouzalessa** [MozillaFoundation/Design#291]
### For Stakeholder Approval
[Fellows Poster](https://mozilla.invisionapp.com/share/JTOARBH7SFP#/324677559_Poster-Fellowships_A1)
[Awards Poster](https://mozilla.invisionapp.com/share/JTOARBH7SFP#/324677557_Poster-Awards_A1)

### Specs
 - **2 posters**
 - **Sizes:** A1 and A2 (same artwork, 2 sizes)
- **Content: [here](https://docs.google.com/document/d/1hh0Nf_-EmIDOT5SG-7Vo0cJZlbKays2CGTv-3robqho/edit?usp=sharing)** - MOZILLA FELLOWS and MOZILLA AWARDS sections
-  **Deadline:** ??
- **STATUS:** A1 posters done. Waiting on Melissa and Ann Marie's approval before making them in A2 size and sending to print.

### Editable Artwork (for designers)
[A1 size here](https://drive.google.com/open?id=1hqS6gaTQRkQAIqwGHhWyqgas3HARlpwP)

### Printing checklist 
I usually follow those steps when sending the material to print. Just leaving those checkboxes here in case they can be useful:
- [ ] approved by stakeholders and design team
- [ ] all images are in CMYK
- [ ] all images are in 300ppi
- [ ] no double spaces between words
- [ ] line break is good and comfortable to read
- [ ] copy is correct (spelling, is there any placeholder copy, punctuation, capital letters rules)
- [ ] bleed marks
- [ ] zoom in/zoom out: any design issues? Alignment, colors?

cc: @kristinashu @xmatthewx

**Comment by taisdesouzalessa** [comment]
@Melechuga and @annmarie123 after conversation with designers and with Ann Marie, we now have a new iteration of this artwork, with more colors while still staying true to our brand guidelines. 

Here are the posters (size A1)
[Fellows Poster](https://mozilla.invisionapp.com/share/JTOARBH7SFP#/324677559_Poster-Fellowships_A1)
[Awards Poster](https://mozilla.invisionapp.com/share/JTOARBH7SFP#/324677557_Poster-Awards_A1)

Any feedback on that please post in InVision. If they are good to go, please let me know :).

I'll follow the same direction for banner, paper banner that hangs and other materials. I'll post them here as soon as I finish them.

**Comment by kristinashu** [comment]
#### Feedback in InVision is:
- URL should be foundation.mozilla.org/fellowships instead of foundation.mozilla.org
- Update copy from: 
  - "**Mozilla Awards support open science.** Like Mozilla Open Science Mini-Grants, which empower projects that make scientific research more open, accessible, and transparent." 
  - to "**Mozilla Awards support the next wave of responsible technology builders.** Like the Responsible Computer Science Challenge, which supports the integration of ethics into undergraduate CS curricula."

@Melechuga and @annmarie123 do you have any additional feedback?

Also, is it absolutely necessary to have these in both A1 and A2, or is A1 enough? Design team is totally swamped at the moment 😬

**Comment by xmatthewx** [comment]
Let's do the larger size. We can scale down and print at Rav if they prove to be too large.

**Comment by annmarie123** [comment]
@kristinashu Last comment I made in invistion for Awards Poster is that it should read "promising approaches" instead of "diverse approaches." I also agree with Matthew that A1 should be enough. 

Also, just to clarify the foundation.mozilla.org/fellowships should ONLY be on the fellowship poster. The URL for all other posters and materials are just the foundation site and perfect as they currently are. Feel free to print after those copy changes. THANK YOU TO ALL OF YOU WORKING ON THIS!

**Comment by kristinashu** [comment]
Ok thanks for clarifying! Will do.

**Comment by kristinashu** [comment]
@annmarie123 here's a pdf of the posters for you to review: [Poster-Fellowships_and_Awards_A1.pdf](https://github.com/MozillaFoundation/Design/files/2474513/Poster-Fellowships_and_Awards_A1.pdf)

I made those two copy updates and then updated the url on the Fellowships poster.

If all looks good then I will export for print!

**Comment by annmarie123** [comment]
@kristinashu perfect! Go ahead and export for print!

Out of curiosity, will this print out be double-sided (i.e. front = fellowships, back = awards), or do you have some other branding/ content for the back already in place to be used?

**Comment by kristinashu** [comment]
I'm assuming these are two single-sided posters. They could be posted on walls or hang from the table. But I'm just jumping in so not completely sure. @xmatthewx would you know?

**Comment by annmarie123** [comment]
Thank you for checking, @kristinashu. Not worth putting too much concern into, as I do know you are swamped. Was truly just curious. Go ahead and continue pushing the items to production + printing. Thank you again!

**Comment by kristinashu** [comment]
Ok cool. Stay tuned for the Festival Guide insert!
