### ISSUE TITLE
Brand Standards: Text and Logo Lockups

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/Design#334]
### Description

Standardize margins/alignment for lockup applications used across foundation properties and document a template. Creating a template with guides and placeholder for type weight, colour and size so we can cohesively set type for programs/initiatives. 

**Reference**
https://mozilla.design/expression/
https://assets.mofoprod.net/network/images/MoFe-2019_Brand-Overview.format-jpeg.jpg

**Example programs/initiatives to test**
https://foundation.mozilla.org/en/fellowships/
https://foundation.mozilla.org/en/initiatives/responsible-cs/

cc: @kristinashu @natalieworth @xmatthewx @beccaklam

**Comment by sabrinang** [comment]
We should examine lockup hierarchy and use as things across the org have a wide variety of styles:

mozilla above: https://internethealthreport.org/2018/
mozilla below: https://voice.mozilla.org/en
mozilla side by side: https://www.mozillapulse.org, https://foundation.mozilla.org/en/privacynotincluded/, https://mixedreality.mozilla.org
mozilla typed out: https://foundation.mozilla.org/en/awards/, https://www.mozilla.org/en-US/developer/
logo lockup with mozilla: https://mozillafestival.org/, https://developer.mozilla.org
other: https://redpen.io/yj84cdeef896c67a5b, https://hubs.mozilla.com

https://mozilla.design/expression/ This has not been updated in a while or followed but a good reference for margins/proportion

**Comment by xmatthewx** [comment]
This is a good audit. Some of this stuff is definite _no-nos_, and things we should not follow. Mozilla developer is bad. It's okay written out in the header on our Awards page because that's not a logo, it's just a page title. It's fine to write mozilla in text. Hubs is breaking several rules, like "by". Mixed reality just doesn't look right. 

I think that this and privacy not included and most closely follow the written standards and the intention of the original system. the system is incomplete, but this part doesn't feel broken and in need of a fix (accept for which goes on top logo or secondary word). 
<img width="371" alt="image" src="https://user-images.githubusercontent.com/53411/59306115-9b82b500-8c69-11e9-9569-6de28868cae3.png">

MDN and MozFest diverge from this. I think that the logo mark helps hold it together, though I still wonder if using white behind the secondary name would be better. 

In a related note: we should still continue to brand ourselves Mozilla externally, only using Foundation internally unless necessary.

**Comment by sabrinang** [comment]
additional audit slides in brand standards doc (slide 31-32): https://docs.google.com/presentation/d/1mQJOwKj1OQkXlhHOVa2uLX0gRPQ-PffW0B3ffXztk5w/edit#slide=id.g4c309f7714_0_4

**Comment by natalieworth** [comment]
Added logo lockups here https://redpen.io/p/kx1efb4f899538b55e
Would be good to include a standardized 'foundation' one for internal use.
cc @sabrinang @xmatthewx @kristinashu @beccaklam

**Comment by sabrinang** [comment]
Thanks for mocking up the options and colour applications @natalieworth 

I would stick with the three colour option system similar to the mozilla logo and festival logos: 
(primary use) two-colour black and white 
(limited use) one-colour black 
(limited use) one-colour white 

reference: https://mozilla.design/mlogo & https://foundation.mozilla.org/en/docs/brand/design/logos/

It says not use the one color white logo with black or any other color type within the containing shape. I would also avoid using mixed black/white highlight because it would mainly work on medium colour applications use cases (white will not appear on white to appear not left aligned etc.). 

For the iteration when it is capitalized under mozilla (what .design calls “Limited use lockup with secondary text”) it feels more like a title than lockup to me but I prefer this over Foundation being above it ("Primary logo lockup"). So if we are leaning towards an option without highlight, it would be capitalized.

My preference is still following the festival highlight lockup spacing as I think it appears stronger as a lockup unit and has been flexible to use in various applications. The spacing has been refined in the documentation however I think we can explore the weight of the type for small applications (it is currently light but I can see it being regular but I like the current contrast from the bold mozilla type).

**Comment by kristinashu** [comment]
I think we have two different things here:

### Lockups
I agree @sabrinang, our mofo properties should follow your mozfest work. It has clear, well established rules, and has been tried and tested extensively using our real work (print, web, many many different backgrounds, different sizes...).

Spacing/margins are super thought out:
<img width="424" alt="image" src="https://user-images.githubusercontent.com/1068783/59381923-6893fc00-8d11-11e9-8e31-cedbd61b97c7.png">

Different backgrounds, use cases, and font weights are well established:
<img width="424" alt="image" src="https://user-images.githubusercontent.com/1068783/59382442-975ea200-8d12-11e9-8fed-98359c2d6b3e.png">

### Navigation
PNI is different because we don't actually have a lockup for it since it isn't an established initiative. We just use it's name as a navigational element where Mozilla links to fo.mo and *privacy not included is typed out and links to PNI homepage.

<img width="724" alt="image" src="https://user-images.githubusercontent.com/1068783/59382761-4ef3b400-8d13-11e9-80c0-2ff49c49097e.png">

BUT navigation is out of scope for this ticket.

**Comment by beccaklam** [comment]
☝️ Agreed, I'm fine with going forward with mozfest's established lockup style. PNI's lockup will probably change this year/ I feel like PNI is more of a unique micro site then a typical Mozilla property like Fellowships or Awards. We went with a "lock up" more because we didn't have time to come up with a logo/brand style, something we're hoping to do for the next instance!

**Comment by kristinashu** [comment]
Closing this ticket since it is very old and out of date.
