### ISSUE TITLE
Thunderbird Offline Donation Acknowledgement

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#354]
From @stephaniemcv 

> Soft Deadline of May 10, 2019

> Get the tbird acknowledgement copy, logo and Philipp Kewisch's signature vectorized into a png format and into the template Sabrina designed earlier so that we can hand over the collateral to Merkle so they can properly mail an acknowledgement letter to tbird donors.

> https://docs.google.com/document/d/1bM3V_4rzMkstXYYkA69B4YuR-6LPdizb24o383V8B1o/edit

**Comment by sabrinang** [comment]
I'll be building off this donor letter template: https://docs.google.com/document/d/1Z9yVc5unkva3Y1axCZ5j3CmwISBIFDBbcbTqYaxkNoM/edit?usp=sharing

Will this just be the thunderbird logo (without mozilla or with both)?

**Comment by stephaniemcv** [comment]
Just the Thunderbird logo, no mozilla logo.

**Comment by sabrinang** [comment]
@stephaniemcv  
Here is the thuderbird letter template: https://docs.google.com/document/d/1nsdgTkZGNOREe-lN6ucUWM2dsa1u3EzqziLSd9kjhH8/edit?usp=sharing

- For the about page link, I have it linked to https://foundation.mozilla.org/about/ instead of http://www.mozilla.org/about since everything written is about Foundation
- In the footer, I’m using the template footer to include fax 650 396 4541 and foundation.mozilla.org instead of mozilla.org
- instead of italics, I bolded the first bullet point term to match the template
- I didn’t vectorize the signature since it wasn’t pixelated (let me know if it needs to be?)

**Comment by stephaniemcv** [comment]
Awesome! Can you make a png of the signature without vectorizing?

**Comment by sabrinang** [comment]
@stephaniemcv I saved it from the goodle doc you provided and uploaded the png signature separately here: https://drive.google.com/file/d/1ptitvDywYJblMJqSOYRcAr_p25WjSfjK/view?usp=sharing

**Comment by kristinashu** [comment]
Looks like this is all done so I'm going to close the ticket but @stephaniemcv just let us know if you need anything else!
