### ISSUE TITLE
Adding tag button style to style guide

### ISSUE THREAD

**Issue by natalieworth** [MozillaFoundation/Design#374]
## Introducing a new style
_Please answer the following:_

1. What element/ style is being changed?
Proposing that we add the tag element button styles to our style guide.

2. Why it is needed?
We will use this on the Pulse site in multiple places. I'm not sure if there is a need for it yet on the Foundation site, but if we need to reuse it anywhere, it will make it easier for design and developer implementation.

  - [ ] Post proposed brand update in Redpen (for desktop, tablet, mobile)
  - [ ] Request design review from design team via R+/R- in Github ticket
  - [ ] Get feedback from devs

-----

### Design

**Desktop:**
https://redpen.io/pe1dfdc2e863264a9c
https://redpen.io/ct6a5296ed74881c22

**Mobile:**
https://redpen.io/su4a04515d9467da5e
https://redpen.io/tkdaa55b61a316254b

**Screenshots:**
<img width="290" alt="Screen Shot 2019-06-11 at 1 18 46 PM" src="https://user-images.githubusercontent.com/14876567/59303819-df66c180-8c4b-11e9-9af8-3811caaa8514.png">
<img width="475" alt="Screen Shot 2019-06-11 at 1 17 59 PM" src="https://user-images.githubusercontent.com/14876567/59303821-e097ee80-8c4b-11e9-99b7-cad6aa3a0ea0.png">

-----

**After Approval**
  - [ ] Update and merge the Sketch library  _(make sure to comb through and look for unlinked symbols that may be affected)_
  - [ ] Update documentation: https://foundation.mozilla.org/en/docs/brand/
  - [ ] Open implementation ticket to ask devs to update Dev [style guide](https://foundation.mozilla.org/en/style-guide/)
  - [ ] Create a dev implementation ticket (following the design to dev hand-off outline)

## Design Reviewer Checklist
_An issue template in github_
**For design review:**
  - [ ] Is this change justified or are we able to use existing brand elements?
  - [ ] Is the development time viable?
  - [ ] Provide an R+ or R- in the ticket
  - [ ] List reasons for approving or denying changes

cc @kristinashu @sabrinang @beccaklam @xmatthewx @natalieworth

**Comment by natalieworth** [comment]
@mmmavis and @youriwims I know you're both really busy with the Pulse site stuff, so just flagging you in this ticket for you to review when you get to it. Essentially, we will be proposing the new tag styles in Pulse for our style guide https://redpen.io/p/fpbbbcc456e7a03d63

**Comment by mmmavis** [comment]
Design looks good ✨ . The only question I have is how should a loooong tag on mobile look. This might be rare case but what if there was a super long tag that couldn't fit into one line on mobile? Do we wrap it, cap after certain number of text, or ? I think it's unlikely that we will hit this issue on Pulse but if we are planning to use the same button style on blog tags on Foundation site, we should take edge case into consideration since blog tags can be looooong. 😂

**Comment by mmmavis** [comment]
@kristinashu @natalieworth - since now both Foundation site and Pulse use the pill buttons, we should standardize the styling and officially add this new button style to our style guide (both in Sketch and the codebase)

Could you let @youriwims and me know once we have given this new button style a name (e.g., `.btn-something`) and added to Sketch as a symbol? Devs will use that as reference and update code in Foundation site and Pulse. Thanks!

**Comment by kristinashu** [comment]
Closing this ticket since it is very old and out of date.
