### ISSUE TITLE
Write chapter on Style

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/Design#4]
Style
* Color
* Icons
* Photography
* Illustration
* Iconography
* Typography

Makerstrap is worth a mention here. http://mozilla.github.io/makerstrap/demo/#/

**Comment by vazquez** [comment]
## Colour
Webmaker offers a colour palette ready for immediate use in the Webmaker suite. This colour palette features similar saturation colours for added visual cohesion.

![screenshot 2015-01-05 10 10 08](https://cloud.githubusercontent.com/assets/1119821/5618788/5d6d5a84-94ea-11e4-887e-6c2ff562e7cd.png)

For use, the Bootstrap theme already has established LESS variables for each colour in the palette. As an example, we can simply declare a CSS colour value by writing `background-color: @lightgrey`. It is not recommended for you to use the HEX value (eg. #E3EAEA) when stating the value of a colour, as it will make the value hard to maintain in the future.

When using colour, adding texture is encouraged if the use warrants it. As an example, we might want to add texture to a coloured background in order to increase its depth and aesthetic. An example of a textured colour can be found below:

![background](https://cloud.githubusercontent.com/assets/1119821/5618796/6f027996-94ea-11e4-8163-92a8cdea7f07.png)

Beyond the technical aspects of colour on the web, colour exists as a powerful communicator. Although a website is not a static two-dimensional image, the colors will either work for or against the content. There is no gray area. As an example, using yellow may reinforce the warmth and cheerfulness of a tropical resort's site, but it could also hinder a law firm's site with its connotations of cowardice. We need to treat the symbolism of color as seriously as the design of graphics and layout. At the very least, the timeless associations of color should be considered. Because Webmaker caters towards a global movement , we must investigate all aspects of regional colour symbolism to expand our global sensitivities. 

Colour also has a capacity to mutate technically. Some colours may display much darker on some screens than others. When using dark colours, ensure that you preview the design on different screens and and web browsers to ensure the best possible result.

Further reading:

[Color Theory for Designers, Part 1: The Meaning of Color](http://www.smashingmagazine.com/2010/01/28/color-theory-for-designers-part-1-the-meaning-of-color/)

[Color Theory For Designers, Part 2: Understanding Concepts And Terminology](http://www.smashingmagazine.com/2010/02/02/color-theory-for-designers-part-2-understanding-concepts-and-terminology/)

[Color Theory For Designers: Creating Your Own Color Palettes](http://www.smashingmagazine.com/2010/02/08/color-theory-for-designer-part-3-creating-your-own-color-palettes/)

[The Code Side Of Color](http://www.smashingmagazine.com/2012/10/04/the-code-side-of-color/)

**Comment by vazquez** [comment]
Webmaker uses the open-source font toolkit [Font Awesome](http://fortawesome.github.io/Font-Awesome/) to source most of our iconography. Icons in Webmaker are used monochromatically in all-white or all-black versions. Font Awesome makes it easy to implement scalable vector icons that can be customized in size, colour, etc. Should you need to use custom iconography, create an SVG asset in order to allow for full scalability on our array of supported layouts.

Aesthetically, we do not use drop-shadows in our icons. The only exception are cases where icons are using a `fa-5x` CSS class, which will increase the font-size of the icon. 

Icons with a `fa-5x` class can use a text-shadow:

`text-shadow: 0 0 0.2rem 0 rgba(0, 0, 0, 0.15)`

**Comment by vazquez** [comment]
## Photography

Webmaker uses photography to showcase our diverse and growing community. Mozilla has curated thousands of photos throughout the years accessible on its [Flickr](https://www.flickr.com/photos/mozilladrumbeat/favorites/) page. When using photography, you are free to use any of the photographs on the Mozilla Flickr profile. You are also free to use any royalty free and publicly accessible photograph.

In regards to photographic treatment, we use both original and stylized photo assets. A stylized photograph is normally desaturated and given a colour tint. An example of this can be seen below:

![img-home-banner-assets](https://cloud.githubusercontent.com/assets/1119821/5760288/80a326a0-9ca1-11e4-9e94-16d066fc6974.jpg)

There are no specific values to keep in mind when stylizing an image. However, Adobe Photoshop is the best application to use for the latter as it provides excellent image manipulation tools.

Here are some tips when stylizing a photograph using Photoshop:

- Modify the 'Hue/Saturation' adjustment
- Increase the 'Curves' of the photograph
- For parts of the image that seem to have little contrast, add a Layer Mask and lightly brush over the part of the image to increase its contrast.

Free stock photography for use and/or inspiration ([CC Attribution 3.0](http://creativecommons.org/licenses/by/3.0/)):

[Little Visuals](http://littlevisuals.co/)
[Unsplash](https://unsplash.com/)
[New Old Stock](http://nos.twnsnd.co/)
[Gratisography](http://www.gratisography.com/)
[Get Refe](http://getrefe.tumblr.com/)
[Picography](http://picography.co/)
[IM Free](http://www.imcreator.com/free)
[Public Domain Archive](http://publicdomainarchive.com/)
[Raumrot](http://www.raumrot.com/10/)
[ISO Republic](http://isorepublic.com/)

**Comment by cassiemc** [comment]
This seems duped by the Webmaker repo's readme & wikis. Thanks for all that work @vazquez, webmaker is very well-documented!
