### ISSUE TITLE
Link styling for "h2-h6" text treatment in the CMS

### ISSUE THREAD

**Issue by taisdesouzalessa** [MozillaFoundation/Design#428]
**Issue:**
Currently in our CMS we don't have any visible sign that a text fragment is a link unless the user hovers over the link. Example below: Mozilla Manifesto is a link but nobody would guess it :)
<img width="1096" alt="image" src="https://user-images.githubusercontent.com/22157921/68886432-12feb980-06cc-11ea-8eff-d364bf77c7b2.png">

**Solution:**
Designers to think about a way to make links more visible that works with our current design system. After that we can talk to engineers about implementation in the CMS.

cc @kristinashu @sabrinang @beccaklam @xmatthewx @natalieworth

**Comment by kristinashu** [comment]
Thank you for opening this! It's been on my mind... I believe the reason we don't show links is because these styles are headings and it would look _maybe_ odd to make entire titles blue or underlined.

Example from prod:
<img width="1178" alt="image" src="https://user-images.githubusercontent.com/1068783/68887144-4aba3100-06cd-11ea-8f0f-ee23af7fa9f1.png">

So **_maybe_** it isn't about showing links in headings but about adding a new larger body style to satisfy our need for larger call out text or intro text. This way, we can stop using headings for intro text and use a new additional body style instead. 

Would love to hear other thoughts/ideas tho!

**Comment by kristinashu** [comment]
This seems related to https://github.com/MozillaFoundation/Design/issues/368. @natalieworth @taisdesouzalessa could this be one ticket?

**Comment by sabrinang** [comment]
Note: include evaluating H6 styling usage (example: how it should appear in bylines) and when it has visible link treatments

**Comment by sabrinang** [comment]
I made screenshot references if all heading links turned blue to be evaluated here: https://redpen.io/p/nq583d7cf4ae68a700

**Overall suggestion**
- Linked heading styles added from wagtail paragraph and image text components should be blue 
    - _Also, could be paired with a guideline tip of when to link a heading and when to add a "read more" type link instead (inconsistent across pages)_

- Heading titles h5/h4 and h6 from blog feeds, pulse feeds, people directory feeds (and "latest news" on home page I'm considering kinda of like a feed) to remain black/gray
   - _Also, should blog feed align to h5 to match people card and pulse feed? or vice versa to be h4 to match blogs?_

**Comment by kristinashu** [comment]
Thanks Sabs! I like h6 in blue but agree that h5/h4 should remain black in feeds. I think the issue described in this ticket is more about when we use a heading style as paragraph text to try and make the text stand out. 

Example creen cap from prod: https://foundation.mozilla.org/en/internet-health/ 
<img width="787" alt="image" src="https://user-images.githubusercontent.com/1068783/79487190-b847f180-7fcc-11ea-9b34-924341bcd302.png">

Here there is a link in the text but it isn't noticeable. My suggestion perhaps is that we need to add a new paragraph style that is similar to some of the heading (zilla and larger than body copy) but is paragraph and would style link in blue.

**Comment by sabrinang** [comment]
Revised these pages:
- https://foundation.mozilla.org/en/internet-health/ _(h4 link changed to body-large as lead copy and removed redundant ‘read…’ link)_ 
- https://foundation.mozilla.org/en/internet-health-report/ _(aligned to use h4 and removed hyperlinks since ‘read…’ link was present)_

________________________
Evaluated the link styling treatment use cases with @mmmavis and had some thoughts:

**Wagtail**
- Since there are not many use cases where we want heading links seen (users should be encouraged linking in body copy, buttons and ‘read mores’) so we are leaning to keep heading styles as is to not show (users can still link in component) as it might get too blue if user chooses to link a lot of headings or part of a heading which wouldn't be ideal
- If users need more options to make links more prominent we can consider including a 'read more →' component instead or include it as linkbutton styling option since we do have .cta-link defined
- +1 to introducing a new paragraph style rather than linking headings if needed

**Related thoughts on areas outside Wagtail**
- blog and pulse feeds: Links should remain black
    - people feed: we also thought to keep this black as well since image is linked, the twitter/linked in icons are black, and other feeds are black as well 
- feed styles: we discussed the pulse feed cards and blog feeds cards (should we be deliberate to align the heading styles or distinguish pulse cards more differently because it isn’t clear to the user what type of content the cards leads too - exp: to add pulse “category” etc. ) 
- h6: We were unsure if we wanted to make h6 the exception and looked at the blog byline use case, we think that formatting it similarly to the feed could help distinguish categories from author/date that can be in body-small:
![blog-byline-idea](https://user-images.githubusercontent.com/2492510/79614300-19e38b00-80b5-11ea-95e2-a844a6ba8c5e.jpg)
- Home page is going through redesign so consistency of ‘read more’ links can be revised then with content

@kristinashu - any more thoughts on this issue?

**Comment by kristinashu** [comment]
These are all excellent solutions! Could you please open two tickets for design to follow-up on and then this should be good to close? 

> feed styles: we discussed the pulse feed cards and blog feeds cards (should we be deliberate to align the heading styles or distinguish pulse cards more differently because it isn’t clear to the user what type of content the cards leads too - exp: to add pulse “category” etc. )

One ticket to explore how to differentiate Pulse and Blog feeds.

> h6: We were unsure if we wanted to make h6 the exception and looked at the blog byline use case, we think that formatting it similarly to the feed could help distinguish categories from author/date that can be in body-small:

Another to explore the blog category vs byline and date. I like how you've separated these, I would maybe up the category above the title but that can be explored in the new ticket!

**Comment by sabrinang** [comment]
I opened two tickets related to issues discussed and closing this issue:
- Differentiate Blog + Pulse Feed Components #542  
- Formatting Blog information: category, byline and date #543
