### ISSUE TITLE
MozFest pitch document

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#463]
Make a design pass of the google doc to "make it look pretty".

**Comment by gideonthomas** [comment]
Sarah is going to connect with Kevin since he's writing copy for this. Copy isn't ready yet.

**Comment by kristinashu** [comment]
Sarah has shared the very WIP copy but it's still isn't ready yet. Doc will be 1 or 2 pages. 

cc @sabrinang

**Comment by kristinashu** [comment]
[Copy doc](https://docs.google.com/document/d/1j43TbEUHx6iSWcYtczm-FjCllKWJFfUR_swHzM8x0c8/edit?ts=5e4c33cb) is ready for design to start shaping it up although Bob will most likely make some copy updates later.

**Comment by natalieworth** [comment]
@kristinashu I started this deck and made a [design copy here](https://docs.google.com/document/d/1uiuJp-Hi2bLKBrA_Hmy4Q7_iusBjfx2GUEl1Dl8Pfto/edit?usp=sharing). Some of the information on the last couple pages repeats, so I didn't know if that had to be formatted too or what the best version was? I'm traveling on Monday so will be out for a bit—but should have time in the evening if Bob needs it asap.

**Comment by kristinashu** [comment]
@natalieworth @sabrinang could I please get a quick design review of these MozFest sponsorship docs for Jesse W? These will be printed today.

- Mozilla Festival - Sponsorship Overview: https://docs.google.com/document/d/1kdteMwDaIBkjjMDXYAn5wOuolqanAANz1W-MumtRkUg/edit?usp=sharing
- Mozilla Festival - Presenting Sponsor: https://docs.google.com/document/d/1yuNIVNW6o_X7saIliA6OkOJButmTOXjF-MdnNlYujAg/edit?usp=sharing 
- Mozilla Festival - Sponsor Spotlight: https://docs.google.com/document/d/1IO7mVACcYSLZloRvJDDzY4wpxgvEbn_FJVjqyu-TdBs/edit?usp=sharing

Not as big of a rush, but here is the updated One-Page doc too https://docs.google.com/document/d/1QdInlwAamUKZqoIhpUwNFDjcYB6ixYdoUS86R6YHqQg/edit?usp=sharing. I've flagged to the mozfest team that it isn't actually one-page and if they're ok with that or if they want to reduce the copy.

**Comment by sabrinang** [comment]
**Overall** 
Banners, body copy and tables styling look good and consistent for all docs. 

**Copy** 
The Presenting Sponsor one is the only one that has "... package" in the banner - is this intentional? Also, should "sponsor spotlight" be "sponsorship spotlight" to be consistent with others?

**Headings**
On print it would be nice if the highlight appear after for the headings to frame the text but I can't seem to make a highlight when I put a space after the title so should we remove the first space then for balance? 
<img width="726" alt="image" src="https://user-images.githubusercontent.com/2492510/75196260-77400900-5710-11ea-9352-1dfc51f3c0e1.png">

**One-page doc** 
For the last page, the bottom info could be placed in the footer section of the doc and probably be formated like the `Mozilla Foundation - Letterhead Light Footer Template` with the line separating it (or dark footer but it may be heavy) 

<img width="1542" alt="image" src="https://user-images.githubusercontent.com/2492510/75196590-2ed51b00-5711-11ea-8ee3-2c651d4fc58e.png">

**Comment by kristinashu** [comment]
Thank you @sabrinang! I've made those style updates and have just asked Jesse about the titles.

**Comment by natalieworth** [comment]
@kristinashu Looks great! I didn't notice any design things that stood out.

**Comment by kristinashu** [comment]
Ok thanks Nat!

Gonna close this ticket and we can work from https://github.com/MozillaFoundation/Design/issues/487 once copy has been finalized.
