### ISSUE TITLE
[Brand] Research Pages on Wagtail

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/Design#472]
### Intro
Coordinate with @taisdesouzalessa how to create and add research hub content to the brand wagtail docs.

### Goal
To publish and populate reserach content to the content or process section of the brand page.

### Process
- collect or create research content that inform pages or IA
- create drafts for review and gather feedback from collaborators
- revise, refine and publish

### Related Issues
Brand Brief: https://github.com/MozillaFoundation/Design/issues/445
Brand Planning Outline: https://github.com/MozillaFoundation/Design/issues/427

cc: @kristinashu @natalieworth @taisdesouzalessa

**Comment by taisdesouzalessa** [comment]
This work is dependent on #4302 - once we share the report with staff we will publish them in Wagtail and it will be the first report in our Research Repository.

**Comment by taisdesouzalessa** [comment]
Sent a message to researchers at the Foundation and people who touch data (like Arliss and Abdoul) and they are all on board in having a centralized place for research. Will coordinate with them this week (March 23rd) in how we can tackle a quick MVP together.

**Comment by sabrinang** [comment]
Sounds good, if there is a lot of content from research that is gathered for the centralized hub might make sense to consider child page(s) direct under `/docs` (like https://foundation.mozilla.org/en/docs/process/ seeing that we have that too now) instead of under `/docs/brand/` but happy to chat if I can help as this goes

**Comment by sabrinang** [comment]
note: related to meta-ticket for /docs content https://github.com/MozillaFoundation/Design/issues/515

**Comment by taisdesouzalessa** [comment]
Sent a message to researchers/data people at Foundation (via Slack) with a template spreadsheet to collect links: https://docs.google.com/spreadsheets/d/1YQHHxIXAb2DKOTOHkV6AKdYGLvv1w07me1VsC1x28es/edit?usp=sharing

**Comment by kristinashu** [comment]
@taisdesouzalessa I think the scope of this should be more about documenting our design team research (eg Stakeholder interviews and analytics dashboard). We can lead by example here!

**Comment by taisdesouzalessa** [comment]
Sounds good to me. I like the idea of leading by example and hopefully inspire others to have a shared repository of research.  I can start adding documents to this section in the next sprint then, since I don't depend on anybody else.

**Comment by taisdesouzalessa** [comment]
We have some projects from our engagement team that can be in this section:
- Internal Stakeholders Report
- MozFest user testing
- PNI Data Studio dashboard

I was thinking that we could build the bulk of this project on Airtable in a Gallery View Mode ([see example here](https://airtable.com/shrPm5L5I76Djdu9B/tbl4aOKkW7qDREYvl/viwjoRdGUtrCMtLvR?blocks=hide), second tab, "hackathons") and link from the wagtail site to the Airtable tab (1 tab will be for user research and 1 tab will be for data dashboards). 

**Why do I think this is a good process:** staff is already on Airtable and they are used to visit it frequently so it is an environment they are familiar with. Also it has searching and filtering capabilities, which allows quick access to information they need. Chances of using our insights are increased if we use Airtable as the main platform. 

The site repository (Wagtail) can point to Airtable so contractors can have a glimpse of the information we have available and request Airtable access if needed (I think there is a way to make a certain tab public if necessary, I just don't know how yet).

What do you think of this proposal @sabrinang @kristinashu @natalieworth @beccaklam ?

**Comment by beccaklam** [comment]
I think it's a neat idea @taisdesouzalessa and the thinking behind it is sound. My only concern though is that staff mainly use Airtable for planning not document repositories. For example, I actually don't use Airtable that often (I should more often probably) and wouldn't look for research there. I wonder if a google drive repository would be better given that staff use that heavily? Or are we worried about privacy?

**Comment by taisdesouzalessa** [comment]
Good thinking, Becca. I wonder, and maybe Kristina may help us with that, who is the most likely group to use the information to make decisions. My thinking was leadership (that is why I recommended Airtable) but it is a good point to make it accessible to all staff. Do you think if we have a link from Wagtail (the research repository) to Airtable, people would be more likely to use it? They can bookmark the URL and access it.
My fear about using a Google Drive repository is that people will forget about it, since we have so many documents there already. Also I wanted an easy to use interface to scan (with image, summary of research, links). Do you have any examples on how we could achieve a similar result on Google Drive? That would help me visualize the solution there.

**Comment by kristinashu** [comment]
Interesting idea Tais! I see there are lots of benefits to using airtable but since we already have so many resources on our wagtail docs page and we're trying really hard to make that our one stop shop for everything, we should put the research work there as well. I pattern we are using is to show the thumbnail of the resource and then link to it in google drive. For your audience questions, I actually think that the main audience for this research work right now is us.

**Comment by taisdesouzalessa** [comment]
Considering the discussion above, here is the first item of our UX Artifacts page:
https://foundation.mozilla.org/en/docs/brand/process/ux-artifacts/

Should we make it public since the access to our Google Docs are closed (just Mozillians can see the content of them)? I feel that is easier for staff to access it - no need to be logged in wagtail. What do you think @sabrinang?

**Comment by sabrinang** [comment]
@taisdesouzalessa Yes, feel free to publish once it's ready (which it looks like it is) and yes access will be controlled on the gdoc sharing controls itself. _You may need to publish the parent page too (if it doesn't appear)._

**Comment by taisdesouzalessa** [comment]
Thanks @sabrinang. Page is now public. I guess the work now is to update the page with past research as well (like MozFest user testing) and some analytics dashboards? Let me know what else you need from this page :).

**Comment by sabrinang** [comment]
Thanks @taisdesouzalessa for publishing the page. Yeah, we can update the page as we come across more research related links and resources from past to present so feel free to use your judgement to add research resources.

**Comment by taisdesouzalessa** [comment]
I am closing this ticket @sabrinang since the first item has been published and now we just have to add new things. Feel free to reopen if you still need this ticket.
