### ISSUE TITLE
Enhance ShareProgress page template

### ISSUE THREAD

**Issue by xmatthewx** [MozillaFoundation/Design#517]
### Intro

Advocacy is seeking to advance our capacity to use ShareProgress. There are two primary types of use cases. This issue is just focused on one of them. 

- A) In scope: We email existing supporters a request to share something to spread the word. 
- B) Out of scope: A user on our site is asked to take action and then share something.  

For Use Case A, advocacy would like to be able to use the standalone ShareProgress "page" for this purpose. For existing supporters, this allows us to send people directly to a page with a full share request.Currently, if we send them to our site, it's a 2 step process. And, advocacy is not be able to test messaging on the first page. But on the standalone page, ShareProgress allows campaigns to a/b test different share messages, track the results, and leverage the winning messages.  

 - This tool could in theory also be used for other engagement efforts. But, it should be used with existing subscribers/followers. New audiences should be sent to our website to pull them into the fold. 

### Status 
I've reviewed "page" and "wrapper" customization in ShareProgress. It is very basic, and will require simple CSS. But, we can add good looking styles, footer and header. It must be kept very basic. 

### Deliverable
 
 - design the simplest page wrapper possible for a shareprogress page. 

### Current example 

<img width="400" alt="image" src="https://user-images.githubusercontent.com/53411/77580407-522aeb80-6eb2-11ea-9bbe-b78ebe891751.png">

### Engineering

A couple of engineering questions. 
 - The answers appear to be no. So design should assume that nothing is possible until proven otherwise. 
 - Can we upload images that shareprogress hosts? Or do we have use inline svg?
 - Can we add a CSS file, or do we have to do it in the html head? 

### Etc

cc: @kristinashu

**Comment by xmatthewx** [comment]
Note on engineering: there's no feature to upload images or cash. So we have to do things in the template or hosted elsewhere.

**Comment by sabrinang** [comment]
Update: Meeting with Kaili/Kristina today

- Get access to ShareProgress _(check with Cade)_
- Landing Page: 
   - create a new default Mozilla branded wrapper and editable components include heading logo, background colours etc.
  - ensure this links to Mozilla's privacy policy _(check with Abigail)_
- Buttons: customizable as well

**Comment by sabrinang** [comment]
I got access to ShareProgress and dev ticket here: https://github.com/mozilla/foundation.mozilla.org/issues/4651

**Comment by mmmavis** [comment]
> there's no feature to upload images or cash. So we have to do things in the template or hosted elsewhere.

We also need to check whether or not ShareProgress blocks linking to external stylesheet / files.

**Comment by sabrinang** [comment]
Started to look into the tool and will be taking design notes in this doc: https://docs.google.com/document/d/1-Ux7b9alzKBkLBNb96eG4lowKwJDH9kmoCR0HuwJyag/edit?usp=sharing

**Comment by sabrinang** [comment]
Updated doc notes with wrapper mockup idea and questions to go over with Mavis tomorrow

**Comment by sabrinang** [comment]
Working with @mmmavis  as she building out a WIP wrapper with updated design: https://github.com/mozilla/foundation.mozilla.org/issues/4651#issuecomment-632937942 

**Some remaining things to adjust:** 

- [ ] Replace http://shpg.org/images/icon-copylink-sprite.png
- [ ] Replace http://shpg.org/images/icon-sharing-below.png or hide
- [ ] Export email icon, facebook icon, twitter icon
- [ ] Alternative character ►
- [ ] Clean up copy/paste text boxes
- [ ] include footer policy links
- [ ] hide existing footer links

**Things to note:**
- ShareProgress’ privacy policy is very dated (2013) 
- There is an assumption it has been reviewed in the past if a contract was signed but isn’t clear if this has passed security review – can we check this? _(the tool and practices just feel very out of date)_
- Use case still aren’t that clear to me if these pages will divert traffic away from our main website from existing email supporters since these pages are not connected to our website in anyway – should we connect this back to foundation.mozilla.org? 
- Even though if it is used with existing subscriber/followers, we’d want them to be pulled into our website somehow or in case new audiences stumble upon this share page too 
- We can’t change the content / share method itself (example: if we want to include instagram as a method to share instead)
- Not sure if there is a better solution to share than this but I'd consider downsizing since the analytics show these pages don’t get a lot of traffic for the monthly 1000usd billed


**Spoke to Kaili she suggested links for the footer:**
Mozilla Privacy Policy: https://www.mozilla.org/privacy/
ShareProgress Privacy Policy: https://run.shareprogress.org/privacy

**Comment by sabrinang** [comment]
@mmmavis 
- asset exports here: https://drive.google.com/open?id=1UvoEz7VEG8rIF_DTHsGTMZvIoavUybjs&authuser=sabrina@mozillafoundation.org&usp=drive_fs
- use → instead of ►
- copy/paste borders use $gray-20 `#cccccc` 1px to align fields

**Comment by sabrinang** [comment]
@mmmavis for the footer:

`Nunito Sans; 12px; #595cf3 ($blue)`
<img width="991" alt="image" src="https://user-images.githubusercontent.com/2492510/82848285-c16b8e80-9ea7-11ea-863c-48f672c2114c.png">
- Mozilla Privacy Policy: https://www.mozilla.org/privacy/
- ShareProgress Privacy Policy: https://run.shareprogress.org/privacy

**Comment by sabrinang** [comment]
Note: as it is outside the scope of page template enhancement, I filed a separate issue to evaluate the usage of after action pages / share flow https://github.com/MozillaFoundation/Design/issues/569

**Comment by mmmavis** [comment]
@sabrinang all image assets seem to include extra border on some sides. Do you mind exporting them again?

**Comment by sabrinang** [comment]
@mmmavis exported again (exported them larger in case there was pixelation too)

**Comment by mmmavis** [comment]
Wrapper udpated! http://share.mozilla.org/352/207160

> use → instead of ► 
We are unable to update this using CSS / HTML only approach.

**Comment by sabrinang** [comment]
Thanks for the update @mmmavis upon reviewing again:
- Can we change the typeface in the copy/paste boxes to be Nunito Sans 14px for both?

- I updated the sprite to match the type size larger and the black stood out too much so I matched the buttons instead: https://drive.google.com/open?id=1VXrdV6NOuyFapzUibd28pUC-4kT5AjTA&authuser=sabrina@mozillafoundation.org&usp=drive_fs

- I thought the icons would look okay keeping boxes and black for aligned contrast but overall I think it is looking heavy and overly boxy. Can you update to these icons without boxes instead: https://drive.google.com/open?id=1UvoEz7VEG8rIF_DTHsGTMZvIoavUybjs&authuser=sabrina@mozillafoundation.org&usp=drive_fs

Everything else is okay and let's just leave the triangle _(thought it was html)_.

<img width="1641" alt="Screen Shot 2020-05-27 at 12 13 30 PM" src="https://user-images.githubusercontent.com/2492510/83062994-54c1d280-a014-11ea-96d8-c2bf6e4aa093.png">

**Comment by mmmavis** [comment]
Updated! http://share.mozilla.org/352/207160

**Comment by sabrinang** [comment]
Nice @mmmavis, looks good on desktop + mobile: 
<img width="400" alt="image" src="https://user-images.githubusercontent.com/2492510/83082422-4d142500-a038-11ea-9922-ee24556e0255.png">  <img width="192" alt="image" src="https://user-images.githubusercontent.com/2492510/83082447-60bf8b80-a038-11ea-9239-f34e37824973.png">
R+

**Comment by kristinashu** [comment]
OMG it looks sooo much better!

**Comment by mmmavis** [comment]
Yay! I'll get someone to look over my code.

**Comment by mmmavis** [comment]
Done.

I've renamed the wrapper to `Default MoFo Wrapper` on Shareprogress.
<img width="781" alt="image" src="https://user-images.githubusercontent.com/2896608/83430699-f5d0d480-a3ea-11ea-8d70-a91a98f1e8ea.png">


Repo for the code https://github.com/MozillaFoundation/shareprogress-wrapper

**Comment by sabrinang** [comment]
Awesome, thanks Mavis!

When I click "Create New Share Page" and for the "Select a wrapper for the page:" default Mofo wrapper is the one that shows up already selected so I think that's fine – closing issue!
