### ISSUE TITLE
Icons for MozFest newsletter

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#579]
From Kristina G:

> I'd like to have 3 icons created for the Spread the Word section of our newsletter. Right now they are wordy bullets that I'd like to simplify with icons to make it easier/quicker to take action.

> 1 - Forward to a Friend - a "forward email" icon that says "Forward to a friend" in text overlay (when clicked this will autogenerate a forward email in their email client)

> 2 - Tweet this - a tweet icon that says "Tweet this" in a text overlay (when clicked this will autogenerate a tweet in another tab

> 3 - Share your work with us - an icon that when clicked takes the user to Mozilla Pulse. Open to suggestions on what this icon could look like and what the text overlay could say

> The next newsletter is June 8. Not sure if that is enough time to design and then test in email before the send, so the next newsletter send is set for July 8, which gives us more time.

Todo
- [x] Check in with Kristina G to make sure you're on the same page
- [x] Create icons based on other existing icons
- [x] Get feedback from Kristina G
- [ ] Export of email

**Comment by kristinashu** [comment]
Ok! Just checking... if we design the icons and layout, are you able to update the template?

**Comment by KGorr** [comment]
@kristinashu I've never done it before, so I'd need a tutorial. I'm not sure who implemented the template to begin with...

**Comment by kristinashu** [comment]
@KGorr I'm not too sure either. @taisdesouzalessa it might be worth checking with Alex on this before getting started to make sure he, or someone, will be able to make the update. Or to at least understand the constraints before starting.

**Comment by taisdesouzalessa** [comment]
slack message with Sketch sent to Alexander and Kristina G so we can all align on what's possible. https://mozilla.invisionapp.com/freehand/document/lhz3ldL0r

**Comment by taisdesouzalessa** [comment]
@KGorr Here are the options for you to choose from: 
[Proposal V1](https://mozilla.invisionapp.com/share/BQXV3G0D2FK#/423183645_Proposal-V1)
[Proposal V2](https://mozilla.invisionapp.com/share/BQXV3G0D2FK#/423183646_Proposal-V2)

I also created an image with a side by side comparison:
[Side by side](https://mozilla.invisionapp.com/share/BQXV3G0D2FK#/423183644_Proposals-Side-By-Side)

I added colors to the "Connect with us" icons because Twitter logo's guideline says their logo should either be blue or white. White doesn't provide enough contrast with the current background color so I had to use blue.

Please let me know what you think about them and your preferred version so I can hand out to Alexander to build.

**Comment by taisdesouzalessa** [comment]
Proposal was updated based on design feedback:
[Proposal V1 (Revised)](https://mozilla.invisionapp.com/share/BQXV3G0D2FK#/423366877_Proposal-Side-By-Side_Original-And-V1-Revised)

@KGorr gave the thumbs up via Slack. Waiting on Alexander to guide me on what he needs for the implementation (svgs or pngs, if he needs specs).

**Comment by taisdesouzalessa** [comment]
[Sent pngs](https://drive.google.com/drive/folders/1lCr_XNi44pamugN6V7OsYyag1j99MWga?usp=sharing) to Alexander as requested by him. I imagine we will have some back and forth as he builds the email but the main task is done. 
I'll close this ticket and only open a follow up ticket if he needs small tweaks in the exported assets.

cc: @kristinashu
