### ISSUE TITLE
Misinfo Monday: July 27th, 2020

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/Design#609]
### Intro

First #MisinfoMonday post on _How to talk to friends about misinformation_ and will need social graphics for instagram feed, story and link preview. It will have corresponding blog post and pocket reading list.

This post will go live on July 27th, 2020.

### Links
moodboard + content doc here: https://docs.google.com/document/d/1ZuE8kuMxd50dupN02n8-L-iVRBggUuGggHOUtaruiC4/edit?usp=sharing

cc: @kristinashu

**Comment by natalieworth** [comment]
Initial designs for this are here: https://redpen.io/p/xub0244aa3a4cb5116
For the branding: It isn't our USUAL moz branding...which I'm kind of wanting to test, but I thought it could be interesting to differentiate these types of content posts. Like the NYT/ Vox/ and the example Audrey shared (and editorial pieces) have branded content that diverges a bit from their corporate identities. I like that something could be recognizable as 'misinfo monday' (since it's reoccurring) instead of 'a mozilla post talking about misinfo' if that makes sense?
but let me know what you think!

**Comment by natalieworth** [comment]
If needed for tomorrow the [working file is in here](https://drive.google.com/open?id=1nN1pTVEDucBxZj_rMYbeKU5nJQRDMO2f&authuser=natalie%40mozillafoundation.org&usp=drive_fs)

**Comment by natalieworth** [comment]
[Final assets and files are in here](https://drive.google.com/open?id=1nHfzFUh8rb_zuyrOOYZXAmMX_vX001Vp&authuser=natalie%40mozillafoundation.org&usp=drive_fs)
