### ISSUE TITLE
Dialogues and Debates: October 13, 2020

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/Design#647]
### Intro
Create graphic assets for the upcoming D&D. Assets may include:
- Screen title cards (Intro, End)
- Social Media (Instagram (post and story), Twitter)
- Blog Post 
- Thumbnails (new tab, youtube/airmo, blog)

### Links
[Planning doc](https://docs.google.com/document/d/1vIsSiTxa5mudaoHC0mnSRx5AAw2AwURzmqzJpTvkH9s/edit?usp=sharing)

cc: @KevZawacki @kristinashu

**Comment by KevZawacki** [comment]
Hi @sabrinang 👋 We have our panelists finalized. I've pasted their headshot below, and also the copy for the main graphic.

A question: Since this is a panel about memes, maybe we can get playful with one of the social graphics and make it a meme itself? Even if it's just the usual treatment, but with white meme text overlaid, like [top] DON'T MISS [bottom] THIS PANEL.

For the main graphic: 

[Mozilla logo]
MozFest Dialogues & Debates
Memes, Misinfo, and the Election
with Kenyatta Cheese, Dr. Joan Donovan, and Brandy Zadrozny
Tuesday, October 13, 8am PT / 11 am ET / 4pm BST

Headshots:

<img width="514" alt="Screen Shot 2020-09-25 at 10 54 31 AM" src="https://user-images.githubusercontent.com/11045250/94282768-35817600-ff1e-11ea-947d-82cb6c79d96b.png">

![Joan D](https://user-images.githubusercontent.com/11045250/94282848-4d58fa00-ff1e-11ea-9af0-c3a9289fb7df.jpeg)

![zadroznyphoto](https://user-images.githubusercontent.com/11045250/94282868-55189e80-ff1e-11ea-9527-52eb04341c74.jpeg)

**Comment by natalieworth** [comment]
Hey @KevZawacki , I [have drafts of these here](https://redpen.io/p/oq94fecbd28cca3e7f)

Is it okay if we keep it meme-less? 😆 I feel like there's a lot going on for each of the slides. I also think the meme style makes it feel joke-y a bit? Like it's a fake thing?

**Comment by KevZawacki** [comment]
Hi @natalieworth, these are perfect 💯  And, good thinking about the meme-style -- let's skip it.

Once the finals are ready, can you send me a note? And, *thank you!*

**Comment by natalieworth** [comment]
Thanks Kevin! [Final files are in here](https://drive.google.com/open?id=1v2AXdIPvrOlp0FsoQPjoB-D5hCzzFt4i&authuser=natalie%40mozillafoundation.org&usp=drive_fs) and I'll also send the link via Slack
