### ISSUE TITLE
Submit Outreachy intern application

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/Design#73]
The design team is interested in submitting an application for an Outreachy intern. @davidascher, are there any blockers we should know about? cc @vazquez 

Here is the application recently submitted for the Youth ID program in Vancouver that we can possibly repurpose: https://docs.google.com/document/d/1lJ4Nb4kZloqiDik_gLpJK5hthkKcVuGgc3Ng9UEIHq0/edit

Deadline for this is Tues Sept 1. @vazquez you had a link for the requirements, can you paste that here?

**Comment by vazquez** [comment]
Copy-pasting the email addressed to all-moco-mofo, containing the requirements:

Thinking of applying to become a mentor? Here are some important things to keep in mind:

- The intern will be working full-time, spending 40 hours a week on their project for three months.
- Participants will work remotely from home. Previously our interns have been based in Greece, Brazil, India, Italy, the US, Canada, and even Australia!
- Internship dates will be from December 7 2015 to March 7 2016.
- We are looking for your commitment to making Outreachy an even better program and would like you to mentor new mentors going forward.
- Your project must be something your intern can do remotely and complete within 3 months.
- We’re looking for exciting and stimulating projects across the org! Groups that have participated in the past include: WebDev, SUMO, Engineering, Rust, Servo, Research, QA/Automation and Community Building
- You will be heavily involved in the selection process for your mentee which will involve interviewing, reviewing code check-ins / bug reports / trial work.

Please speak with your manager to check it’s OK for you to submit an application and ensure your department can support associated costs of having an Outreachy Intern on your team.

Note: For this program we will be selecting Outreachy mentors based on your previous mentorship experience e.g. either you have been an Outreachy mentor in the past, or been a University Intern mentor, or you have been recommended by your manager as someone who would be a great mentor. We plan to be able give new mentors this experience for subsequent programs. Remember that mentoring is about growing the individual and committing to bringing that person forward, at least as much or more than it is about getting the project completed.

Note: in a change from  in previous years, we are asking departments to contribute financially in the following manner. We (Mozilla)) will provide each Outreachy Intern a laptop to keep, out of the mentoring department’s funds, we will arrange travel for them for onboarding/Orlando work week, out of department funds, and we will give them an extra $500 travel grant (They get a similar one from the Outreachy program) to attend an appropriate conference.

**Comment by davidascher** [comment]
Let me find out what our budget can support.

**Comment by cassiemc** [comment]
Any updates @davidascher? Since deadline is next Tues and I'm away in Chicago until Tues evening I'd love the chance to help with this this week before I go.

**Comment by cassiemc** [comment]
Just got the green light from Michael. Woohoo! @vazquez can you do a first pass on the application?

**Comment by vazquez** [comment]
@cassiemc Let me know what you think.

This application needs to be submitted through Google Forms on this URL: https://docs.google.com/forms/d/1MB4TCCB00T6RX3frNrCtlTEesa8yyFiTHJcQR8jkD6s

##### Full Name  
Ricardo Vazquez  

##### Preferred Email Address
ricardo@mozillafoundation.org

##### Department
Design, Mozilla Foundation

##### Job Title
UI Designer

##### Who is your manager?
Cassie McDaniel

##### Does your manager know about and support your request to be an Outreachy mentor?
Yes

##### Will your team commit to funding additional expenses for the intern?
Yes

##### Please describe your mentorship experience, and experience of mentoring in open source

Since 2011, I've mentored students through a Toronto-based non-profit organization named Ladies Learning Code. Ladies Learning code has allowed me to share my passion with others. As a member of the tech community in Toronto, I was searching for a place to collectively boost up participants’ knowledge and skills. When Ladies Learning Code opened their doors, I knew this was the right place to contribute towards a collective that strives to promote web literacy.  

As I'm passionate about extending an open-source design culture to people outside of Mozilla, I started a YouTube live stream series earlier this year where I design with everyone as my audience. Through this pathway, I am able to open our design practice and my mentorship to individuals eager to design but unsure of steps to take.

Teaching has always been an active passion of mine. Through education, I have been able to practice and extend my mentorship skills to different communities. I started the [FramerJS Toronto Meetup](http://www.meetup.com/Framer-JS-Toronto/), a group aimed towards teaching animation principles in prototyping. I also co-organize the [TorontoUX Meetup](http://www.meetup.com/TorontoUX/), where our aim is to connect & engage UX enthusiasts: developers, startups, designers, product owners, and entrepreneurs through workshops and events.

##### Intern Project Proposal Title

Open-Source Designer, Mozilla Foundation

##### Please submit a description of your intern project proposal - 400 words max. Include the specific technical or other skillsets an intern would need to have to be successful.

At Mozilla Foundation, we spend a lot of our energy in promoting web literacy. We’ve been hard at work the past year building innovative tools, supporting communities, teaching, learning, and shaping the environments in which the open web is made possible. We want everyone in the world to create, not just consume, the Web around them.

As an Open-Source Designer, the applicant will be immersed in the world of products such as Thimble and Webmaker for Android, communities such as Mozilla Learning Networks and Mozilla Hive groups, and initiatives such as Mozilla Advocacy and Fundraising.

The applicant will be required to:

- Approach design through an iterative process with our growing user base and community
- Design and implement interfaces and collateral work for our products and initiatives
- Illustrate collateral work for our products and initiatives
- Create and conduct user testing research to generate insights of our products
- Bridge the gap between the behaviour we want users to take and the interface that gets them there
- Prototype and implement work using HTML, CSS, and JavaScript 

##### Yes, sign me up to help make Outreachy@Mozilla even better, and I’m willing to mentor new mentors
Yes

**Comment by cassiemc** [comment]
R+ @vazquez let's do it!! :hand:

**Comment by vazquez** [comment]
Awesome, submitting now :) :hand:
