### ISSUE TITLE
Mozilla News Beat/Byte: January 28, 2021

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#743]
[placeholder]

**Comment by natalieworth** [comment]
Hey @nancyt1 I'm just going to add Xavier's request for a matching News Beat header (similar to the News Byte header) :

From Xavier:
I’m hoping to get News Beat header art that looks just like the new News Byte header but with a yellow-to-red gradient in the background instead of blue-to-purple and a tiny equalizer chart icon instead of Chompy.

**Comment by nancyt1** [comment]
Got [content](https://docs.google.com/document/d/1CFsy9MkKeCyCPaNmTvpQaAAmDFof4zNZHEQtJz_Q66U/edit) for News Beat

**Comment by nancyt1** [comment]
Finished assets are in the [drive](https://drive.google.com/drive/folders/12t1CpMmBGuw4vzXY3vEXDbxCmM6KlrvE) (:
