### ISSUE TITLE
Get quote for explainer videos

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#796]
Work with Audrey to gather info to share with P&G to get a quote for the work.

Follow-up ticket for next sprint would be to gather all the assets together to onboard P&G to the work and process.

**Comment by natalieworth** [comment]
Audrey and I are going to meet with Carly from P&G to discuss this.

**Comment by natalieworth** [comment]
Audrey and I met with Victoria from P&G last week to discuss our needs. For 22 videos, we have a budget of $1300 per video. P&G isn't able to fully create all of them for that much, so they have offered to only provide art direction and storyboarding for each.

I feel that we already have an established direction from Sabrina's trustworthy AI and since the videos are primarily 'talking heads' with possible animations—so I don't think that would be a good use of our budget. 

We're going to reply to Victoria tomorrow as most people are out for the Easter long weekend.

**Comment by kristinashu** [comment]
Was their quote for just the 'talking heads' or for animations as well? Perhaps they could do fewer videos and without explainer animation (just the intro/outro/bumper) animations to bring down the cost?

**Comment by kristinashu** [comment]
kk I think this is on Audrey now and off our plate? if so then please feel free to close :)
