### ISSUE TITLE
Improve the block quote in wagtail

### ISSUE THREAD

**Issue by natalieworth** [MozillaFoundation/Design#806]
### Intro

Update and improve the current wagtail block quote feature.

**Comment by natalieworth** [comment]
- [ ] Audit existing quote options
- [ ] Gather benchmarks 
- [ ] Explore options
- [ ] Share with relevant stakeholders and design team
- [ ] Decide on 1 quote style to update in wagtail

**Comment by kristinashu** [comment]
Consider other related work like this https://github.com/mozilla/foundation.mozilla.org/issues/4877 and via @sabrinang 

> Right now people are using our callout box (for quotes and highlights) but nothing can be styled inside which is showing to be quite limiting to translate from gdocs and not really doing one well. Just for context how quote blocks could be useful elsewhere

![image](https://user-images.githubusercontent.com/1068783/113944640-b8329a00-97b9-11eb-9c58-eff150a28cdb.png)

**Comment by sabrinang** [comment]
I filed in issue to update callout box styling here as well: https://github.com/mozilla/foundation.mozilla.org/issues/6509

**Comment by natalieworth** [comment]
@kristinashu @jamilasnell I talked with Sabs and Nancy during crit, and Sabs is going to be doing a type audit. We also wanted to explore different font options and pairings. Is it okay if I icebox this until we have our typefaces updated? I'm worried about doing this now and then having the engineers change it again if we decide on a serif or something in the future?

**Comment by kristinashu** [comment]
Good call!

**Comment by sabrinang** [comment]
Regarding _single quote block_, additional attribution option is being worked on in: https://github.com/mozilla/foundation.mozilla.org/issues/4877
- I can also explore various column layouts for the single block quote but there may be some overlap with callout block explorations so I will do this afterward

Regarding _callout block_, I’ve looked through the usage of callout blocks on publication pages and it looks sparse/not used.

Callout block examples:
https://foundation.mozilla.org/en/docs/how-do-i-wagtail/grimms-fairy-tales-demo/frog-king-or-iron-henry/
https://foundation.mozilla.org/en/docs/how-do-i-wagtail/grimms-fairy-tales-demo/wolf-and-seven-little-kids/
https://foundation.mozilla.org/en/docs/how-do-i-wagtail/grimms-fairy-tales-demo/little-brother-and-little-sister/
https://foundation.mozilla.org/en/what-we-fund/awards/with-great-tech-comes-great-responsibility/timeline/
https://foundation.mozilla.org/en/data-futures-lab/data-for-empowerment/what-helps-the-ecosystem-for-needs-and-support/
https://foundation.mozilla.org/en/what-we-fund/awards/with-great-tech-comes-great-responsibility/insights-from-tech-workers-today/
There is only 6 live/published (en) pages I found that use the _callout block_ from what I can find and half of them are demo pages and the ones that are not use them to highlight quotes. I suspect these were only used because the _single quote block_ did not exist when publication templates were introduced but were included afterwards so they used them in lieu but perhaps would not have used it otherwise as it isn’t seen on newer pages. 

From the previous responses in the previous call out issue https://github.com/mozilla/foundation.mozilla.org/issues/6509, I think it is due to the lack of styling options for _callout block_ that deters usage to lead to its unpopularity and inflexibility for use. 

Thoughts:
- Is there not enough use cases to justify to keep this or should we discuss with devs what is possible to revise?
- From the use cases, should we just focus on improving _single quote block_ instead?

Explorations for callout block:
- some explorations if we can do various column width, borders and text styling within block
<img width="627" alt="image" src="https://user-images.githubusercontent.com/2492510/148633008-e745f6f7-90d8-4a4d-a063-7b399584bc9e.png">

- link to [figma exploration](https://www.figma.com/file/JT9Dvdyc96AqQ3HJlnA9Qq/?node-id=814%3A259)

**Comment by sabrinang** [comment]
The quote block is being revamped in https://github.com/mozilla/foundation.mozilla.org/issues/4877. For the callout block, due to infrequent use it we won't revise it now. 

@kristinashu R?

**Comment by kristinashu** [comment]
Agree, thank you Sabs!
