### ISSUE TITLE
Coalition Partners Memo: Publication & Graphics 

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#860]
Via Kaili in Airtable https://airtable.com/tbljPmOCkK9JShaTS/viwpFvt3FxiVannif/recFHFraxT1af2d8t?blocks=hide

> I'm working with coalition partners (ADL, OTI, Avaaz, Maplight and others) to co-author a landscape memo that each organization will publish to our own websites. Additionally, we are hoping to have a well designed PDF to share with partners. I think I may be able to publish it to our site with the publication template, or just regular Wagtail, but will likely need a few visualizations (a promo graphic specifically). If the team can offer help with PDF design, that would also help. 

> Timeline and content outline here: https://docs.google.com/document/d/1ggqKPadVT-8Gnhrbl_1gZtMH6hnWOPdUyhjqQQB3d3o/edit

> [Brief](https://docs.google.com/document/d/18bYwOuDH1pEDOdd4adggrKF7D_2fkgTz99PYPLbNuIo/edit#)

Design can provide some support with this but only minimal since it's not really focused for novice audiences. I'd recommend:
- [x] Kaili create the PDF using our template https://docs.google.com/document/d/1PTdSrNA7-2LiTmAISEOzWmPEhUZvbDPjaYp2-JFc8T8/edit
- [x] Design to do a design review of the PDF
- [x] Kaili add the content to the publications template https://foundation.mozilla.org/en/docs/how-do-i-wagtail/publications/
- [x] Design to do a design review of the publication
- [x] Olly to create graphics

**Comment by kaili09** [comment]
The PDF isn't created out of the publications template? It should be in the order outlined above?

**Comment by kristinashu** [comment]
The PDF isn't automatically created. You need to make it in Google Docs and then exported it and add it to the publications header.

**Comment by sabrinang** [comment]
@kaili09 
### **Feedback for Publication Review**
**Header banner**
Consider making the white graphic areas an off-white/grey to lower the contrast so it doesn’t look as visually busy with the white text above _(especially when viewed on mobile)_
<img width="200" alt="image" src="https://user-images.githubusercontent.com/2492510/132583773-7f62c1e9-805f-4fe4-a665-e1a2623c35cd.png">

**Trained for Deception: How Artificial Intelligence Fuels Online Disinformation** 
- Intro notes: use H4 styling for “Executive Summary”
- The thumbnails aren’t displaying the ones uploaded but it is probably because the child pages are not published yet as I can see they have them loaded on their respective pages and look good there.

**Introduction**
- Subheading is “Trained for Deception: How Artificial Intelligence Fuels Online Disinformation” and all the other pages are just “How Artificial Intelligence Fuels Online Disinformation” _(either remove or add “Trained for Deception” for consistency)_

**Ad-Targeting and Delivery** 
- “[Vicious cycle](https://www.google.com/url?q=https://www.newamerica.org/oti/reports/special-delivery)” link is a google redirect link that is same as the link before not sure if this is deliberate _(remove the redirect)_

**Ranking and Recommendation Systems** 
- All other sections have authors but this one doesn’t _(consider including them to keep all the pages consistent since you added them already)_
- Add space before link “… thousands of internet users,[called on Facebook](https://foundation.mozilla.org/en/blog/mozilla-urges-facebook-and-twitter-halt-dangerous-recommendations/) ....“

**Comment by kaili09** [comment]
@sabrinang am I understanding correctly that [this image](https://redpen.io/vb60d73cd828d1e36e) should be even darker?

**Comment by kristinashu** [comment]
Kaili has launch this and it looks great https://foundation.mozilla.org/en/campaigns/trained-for-deception-how-artificial-intelligence-fuels-online-disinformation/ so I'm guessing this is good to close!
