### ISSUE TITLE
[YouTube RegretsReporter shareout] Brief TorchBox devs

### ISSUE THREAD

**Issue by natalieworth** [MozillaFoundation/Design#868]
### Intro

Brief TorchBox on the YouTube RegretsReporter shareout

I will post more information here and make a document when we have more information.

**Comment by kristinashu** [comment]
Brandi, Marnie, and I can work on getting the quote and timeline. Please add any additional context you can think of to [the doc](https://docs.google.com/document/d/1eIwBT3f-vmNUIpvUmGKE_sthc9bG_JRDUrA7ocZO-Wg/edit#). Once that is done then I don't think there will be anything until next sprint when you can review the designs in more detail with them.

**Comment by kristinashu** [comment]
Still waiting for a quote and timeline from Marni. Going to move this to next sprint for us to share the wireframes and mockups with them.

**Comment by wilhitem** [comment]
Update:
* Timeline for Launch shifted to 8th July due to holiday weekend
* Reviewed mock ups w/ dev with lead front end dev for project w/ Kalob 
* Based on feedback from front end dev lead based on timelines 
** prep work for dev's scheduled for week of 21st 
** Brandi is able to move up timeline for research completion to occur before 28th June (hooray!)
** Front end dev will be done by 2 developers over the week of the 28 June-2 July
** Scheduled additional time for a front end dev for July 5th and 6th
* Kalob will break dev work into sub-epics so that those can be split among torchbox front end team and the Moz internal team

This week tasks (marni):
* Schedule time w/ Design and front end dev to go over mock ups/answer questions so that Torchbox can firm up estimates
* Schedule time for Brandi/Jesse/Theo/Kristina/Nancy/Ben H/Tbox dev (Chris Lawson) to review timelines

**Comment by kristinashu** [comment]
Final designs https://www.figma.com/file/Mp4TDFJIi02sYvxLDTCknF/YouTubeRegretsReporter-Share-Out?node-id=1579%3A286

Copy is close to final https://docs.google.com/document/d/1pn8CUywtNo2J3rIlgfIKqCyJor1UiiLGqziHzVi_muI/edit#

@sabrinang is finalizing the illustrations

Nancy will meet with Marni and Chris tomorrow.

Epic for all the dev work https://github.com/mozilla/foundation.mozilla.org/issues/6877
