### ISSUE TITLE
Stickers for HR

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#914]
Lindsay would stickers made that HR will then mail to new hires.

Her brief is here https://docs.google.com/document/d/1GsXo9K6QouE27zRqi2E_kR4sVq0O71tuXExF_KayMbg/edit

The designers are done but they need to be prepared for print.

**Comment by sabrinang** [comment]
@kristinashu Ready for review

Stickers exports here: https://drive.google.com/open?id=1TwuypcdFiIWVqGGfdiLEZ_yW7Pm7cw-g&authuser=sabrina%40mozillafoundation.org&usp=drive_fs

- most exports use stickermules templates _(for die cuts and rounds)_
- the holographic style didn't have a specific template so exported it as both .svg/.ai for you to upload
- common voice sticker wasn't an editable file but reporposed art assets from [figma file](https://www.figma.com/file/L8iLxjZ4mAkBk82mB757qF/cv-marketing-assets?node-id=1992%3A1592) to scale for sticker
- the tree sticker exported with a white border or without as options since it wasn't clear what the final design was
<img width="300" alt="image" src="https://user-images.githubusercontent.com/2492510/134981332-bf625f85-c744-4b3e-a7a7-ef87e945f804.png">

**Comment by kristinashu** [comment]
R+ thanks you Sabs for the speedy work!

Lindsay will be uploading these to Sticker Mule so please share with her as well.

**Comment by sabrinang** [comment]
Shared them with Lindsay last week and supported her through print submissions with Sticker Mule. Followed up today and things went well — closing issue.
