### ISSUE TITLE
[PNI Holiday Marketing] Creative ideation and exploration

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Design#923]
Epic https://github.com/MozillaFoundation/Design/issues/918

[Past Graphics](https://drive.google.com/drive/u/0/folders/1RSyHgGCMe0_9GDt5oNdf1iaNEw45gokg)
[Marketing Plan](https://docs.google.com/document/d/1ReIqLEb74yD_Vexb3RV9-kSR9RKIhMT65vTzKExpoN8/edit)

- [x] Nancy/Becca to roughly narrow down a few different concepts/moodboards (maybe in Google slides)
- [x] All designers meet to discuss, refine the concepts/moodboard
- [x] Share with stakeholders for feedback

**Comment by nancyt1** [comment]
Started a [Pinterest ](https://www.pinterest.ca/mozillafoundationdesign/privacy-not-included/)board!

**Comment by nancyt1** [comment]
[Link to the google slide deck](https://docs.google.com/presentation/d/1gJizF6If-dWmOz1ypDXG_qaWIqqos4zxlqqJ9fCLXj8/edit#slide=id.g25275a8168_0_260)! 
Meeting with Jen and Lindsay on monday!

**Comment by kristinashu** [comment]
I think this ticket is done! Please just add your meetings notes to this ticket, close it, and then move onto https://github.com/MozillaFoundation/Design/issues/924!

**Comment by beccaklam** [comment]
Meeting notes:

Jen C said:
Referring to user testing back in August 2021, most common feedback was that consumers just want to know what to buy and what to avoid. Because of this, it'd be great if our designs:
- Keep it simple, not too busy
- Supports quick glances without giving too much away
- Increase scan-ability across all content

Lindsay said:
- Likes the "Photo mix with doodles" direction, feels that it's very versatile
- Bubble 3D also feels fun and playful

Audrey said:
- Likes the stickers direction, feels that a play on the yearbook "most likely tos" would match the snarky/fun tone of the "honest ad" infomercials that will also be produced for PNI this holiday season
- Sticker direction also feels like it could be remixed for cool GIPHY content

Lindsay and Audrey also requested that we choose only one or two designs to test against the control (Olly's assets from last year) to keep the workload manageable for Audrey when she sets up the ads.
