### ISSUE TITLE
[PNI] Review & update evergreen graphics for PNI homepage

### ISSUE THREAD

**Issue by nancyt1** [MozillaFoundation/Design#965]
- [x] Review evergreen graphics
   - [x] make sure all categories have custom graphics
   - [x] make sure all products shown are up to date
- [x] Replace holiday header with evergreen one

**Comment by kristinashu** [comment]
I think that for now we should just go with the old evergreen version since we might be updating them again soon for Valentines day. At that point, we'll also hopefully have more info about our audience. So I think this ticket should be to review the old evergreen version and then update the site with them. But let me know what you think!

**Comment by nancyt1** [comment]
Updated all english share images and category graphics.

Could no update snippets directly so I edited the previous image to an evergreen one, [bug ticket](https://github.com/mozilla/foundation.mozilla.org/issues/8148) was filed. Also ran into trouble updating promo image of localized pages with localized graphics so I might have to update that later but those are already made.

**Comment by nancyt1** [comment]
Localized share images are in thanks to Theo (:
